### ISSUE TITLE
ESPhome+SmartIR unable to control AC

### ISSUE THREAD

**Issue by Zhangkunchen** [smartHomeHub/SmartIR#1113]
**Home Assistant version**

Home Assistant 2023.8.4
Supervisor 2023.08.1

**SmartIR version**

[1.17.7](https://github.com/smartHomeHub/SmartIR/releases/tag/1.17.7)

**ESPHOME YAML**
```yaml
api:
  encryption:
    key: "RZomQkMqCX1mDf8Ig53ts4SDkpHxKN2Xtz74NgcpBiM="
  services:
    - service: send_raw_command
      variables:
        command: int[]
      then:
        - remote_transmitter.transmit_raw:
            code: !lambda 'return command;'
            carrier_frequency: 38k
            
    - service: send_samsung_command
      variables:
        command: string
      then:
        - remote_transmitter.transmit_samsung:
            data: !lambda 'return strtoll(command.c_str(), NULL, 16);'

remote_transmitter:
  pin: GPIO14
  carrier_duty_percent: 50%

```

**SmartIR configuration**

```yaml

smartir:

climate:
  - platform: smartir
    name: Room AC
    unique_id: room_ac
    device_code: 1183
    controller_data: my_espir_send_raw_command
    temperature_sensor: sensor.temperature_humidity_sensor_080d_temperature
    humidity_sensor: sensor.temperature_humidity_sensor_080d_humidity
    power_sensor: input_boolean.xu_ni_kai_guan

```

**Describe the bug**

**Debug log**

```text





Logger: custom_components.smartir.climate
Source: custom_components/smartir/controller.py:183
Integration: SmartIR (documentation)
First occurred: 22:46:40 (1 occurrences)
Last logged: 22:46:40

Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 382, in send_command
    await self._controller.send(
  File "/config/custom_components/smartir/controller.py", line 183, in send
    service_data = {'command':  json.loads(command)}
                                ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)






```

**Additional context**

**Comment by vassilis-panos** [comment]
I'm closing this topic because it seems that no one in the community has had a solution for quite some time. Thank you.
