### ISSUE TITLE
Possible not well-structrued the version file

### ISSUE THREAD

**Issue by ManuelAbril** [smartHomeHub/SmartIR#112]
**Home Assistant version**: 0.91.4

**SmartIR version**: 1.4.2

**SmartIR configuration**: not applicable but I add custom updater code.
```
# https://github.com/custom-components/custom_updater
custom_updater:
  show_installable: True
  track:
    - components
    - cards
    - python_scripts
  component_urls:
    - https://raw.githubusercontent.com/keatontaylor/alexa_media_player/master/custom_components.json
    - https://raw.githubusercontent.com/smartHomeHub/SmartIR/master/version.json
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/iammexx/home-assistant-config/master/ui/darksky/version.json
```
**Describe the bug**
Custom Updater (custom component for HA) has an error once it tries to check the last version of the SmartIr component. I checked all other card and component URLs I am using and I realize there is a main different between their version files and SmartIr version. For instance:

Dark Sky Weather Card
```
{
    "dark-sky-weather-card": {
      "updated_at": "2019-02-19",
      "version": "0.10.2",
      "remote_location": "https://raw.githubusercontent.com/iammexx/home-assistant-config/master/ui/darksky/dark-sky-weather-card.js",
      "visit_repo": "https://github.com/iammexx/home-assistant-config/tree/master/ui/darksky",
      "changelog": "https://github.com/iammexx/home-assistant-config/blob/master/ui/darksky/changelog.md"
    }
```
SmartIR
```
{            
    "version": "1.4.2",
    "minHAVersion": "0.92.0b0",
    "releaseNotes": "A new version (1.4.2) is available that is compatible with your system. **This version has a breaking change in the configuration!** Call the ``smartir.update_component`` service to update the component.",
    "files": [
        "__init__.py",
        "climate.py",
        "media_player.py",
        "fan.py",
        "controller.py",
        "manifest.json",
        "services.yaml"
    ]
```

Although the error I detailed in debug section is related with "integer", could it be because of the SmartIr version file is not well-structured?
**Debug log**

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 122, in handle_call_service
    connection.context(msg))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1138, in async_call
    self._execute_service(handler, service_call))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1160, in _execute_service
    await handler.func(service_call)
  File "/config/custom_components/custom_updater/__init__.py", line 110, in check_all_service
    await components_controller.cache_versions()
  File "/config/custom_components/custom_updater/__init__.py", line 222, in cache_versions
    information = await self.pyupdate.get_sensor_data(True)
  File "/config/deps/lib/python3.7/site-packages/pyupdate/ha_custom/custom_components.py", line 56, in get_sensor_data
    components = await self.get_info_all_components(force)
  File "/config/deps/lib/python3.7/site-packages/pyupdate/ha_custom/custom_components.py", line 41, in get_info_all_components
    entry[attr] = component[attr]
TypeError: string indices must be integers
```

**Comment by smartHomeHub** [comment]
Custom updater component is not supported. SmartIR is using its own updater

**Comment by ManuelAbril** [comment]
Is it possible to supported it?
