### ISSUE TITLE
Xiaomi Controller support

### ISSUE THREAD

**Issue by thundergreen** [smartHomeHub/SmartIR#114]
Hello people.. Really nice component but i am missing the xiaomi controller. As it is not supported yet I wanna know if it is still on the road map ?

**Comment by smartHomeHub** [comment]
Actually, my xiaomi controller never arrived. Are you willing to test a version?

**Comment by thundergreen** [comment]
Fuck.. and me I have 4 .. yes wanna test a version .. with pleasure :)

**Comment by smartHomeHub** [comment]
:)
Could you send me the accepted parameters of REMOTE.SEND_COMMAND service?

**Comment by thundergreen** [comment]
Where and how would I find them ? in logs?

**Comment by thundergreen** [comment]
@smartHomeHab do I have a xiaomi version present ? I'd like to test

**Comment by smartHomeHub** [comment]
Did you ever use the remote.send_command? Is only enity_id and command required?

**Comment by thundergreen** [comment]
Yes..that's it .

**Comment by smartHomeHub** [comment]
Ok. It is almost done. Did you have already a set of xiaomi commands for your climate?

**Comment by thundergreen** [comment]
Only for media player but I already have the codes for another custom component. I have to use raw instead of base64 right

**Comment by smartHomeHub** [comment]
You can use pronto and raw. Send me the commands of your media device to make a json file for you

**Comment by thundergreen** [comment]
I already made the json file for it



[1040.zip](https://github.com/smartHomeHub/SmartIR/files/3149468/1040.zip)

**Comment by smartHomeHub** [comment]
Please download from the rc branch. Configure the SmartIR component as the example in documentation and create your json files by setting "supportedController": "Xiaomi" and "commandsEncoding": "Pronto" or   "commandsEncoding": "Raw"

**Comment by thundergreen** [comment]
Great! Thanks I will try that and report. I assume mediaplayer and AC are working now with Xiaomi?

**Comment by thundergreen** [comment]
```
2019-05-07 22:04:12 ERROR (MainThread) [custom_components.smartir.media_player] not a valid value for dictionary value @ data['entity_id']
Traceback (most recent call last):
  File "/home/hass/.homeassistant/custom_components/smartir/media_player.py", line 249, in send_command
    await self._controller.send(command)
  File "/home/hass/.homeassistant/custom_components/smartir/controller.py", line 92, in send
    'remote', 'send_command', service_data)
  File "/home/hass/homeassistant/lib/python3.6/site-packages/homeassistant/core.py", line 1118, in async_call
    processed_data = handler.schema(service_data)
  File "/home/hass/homeassistant/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 267, in __call__
    return self._compiled([], data)
  File "/home/hass/homeassistant/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 589, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/home/hass/homeassistant/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 427, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: not a valid value for dictionary value @ data['entity_id']

```

Unfortunately I get this error message with this config:

```
media_player:
  - platform: smartir
    name: Living room TV
    unique_id: living_room_tv
    device_code: 1040
    controller_data: 192.168.1.217
```

**Comment by thundergreen** [comment]
Works like a charm!
Thanks soOoo Much!!!

**Comment by smartHomeHub** [comment]
Nice. Please consider to share your code files.

**Comment by thundergreen** [comment]
u mean json? It is a mi of TV and Soundbar. so i cannot share those :(
