### ISSUE TITLE
Added Configuration but component does not show up

### ISSUE THREAD

**Issue by ekkesa** [smartHomeHub/SmartIR#12]
Hi,

I added the necessary files (__init__.py, climate.py) to custom_components/smartir  and the json file under codes/climate.
The climate.yaml file has the following entry:
- platform: smartir
  name: Living Room Airconditioner
  device_code: 1450
  controller_send_service: switch.broadlink_send_packet_192_168_1_11
  temperature_sensor: sensor.living_room_temperature
  humidity_sensor: sensor.living_room_humidity

I do not see any errors in the log, but the component is not showing up. Did I miss something?

**Comment by smartHomeHub** [comment]
Can you find the component under Developer Tools->States?

**Comment by ginko64** [comment]
Hi there!
same issue here.
I can not find the component under Developer Tools->States.
What can I do?
Thanks

**Comment by smartHomeHub** [comment]
Did you resolve this issue?

**Comment by ginko64** [comment]
I just try to reinstall all the component right now! 
I let you know.
 
Thanks a lot
Mario

**Comment by ginko64** [comment]
Hi Vassilis
unfortunately nothing changed. I cannot find the component in my list of entity.

This is a brand new Hassio installation with the last version available and I have only a few component installed.

This is the log I receive, please let me know if you need anything else to help me to solve the issue. 
Thank you very much
Mario

2019-02-25 11:00:51 WARNING (MainThread) [homeassistant.loader] You are using a custom component for sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-02-25 11:00:54 WARNING (MainThread) [homeassistant.loader] You are using a custom component for smartir.climate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-02-25 11:00:55 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 352, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 239, in async_update_ha_state
    attr = self.state_attributes or {}
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/climate/__init__.py", line 234, in state_attributes
    self.precision),
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/temperature.py", line 22, in display_temp
    "Temperature is not a number: {}".format(temperature))
TypeError: Temperature is not a number: 25
2019-02-25 11:00:56 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.sonoff.switch. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 962, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.sonoff.switch'; 'custom_components.sonoff' is not a package
2019-02-25 11:00:56 WARNING (MainThread) [homeassistant.loader] You are using a custom component for switch.sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-02-25 11:00:56 WARNING (MainThread) [homeassistant.loader] Integrations need to be in their own folder. Change switch/sonoff.py to sonoff/switch.py. This will stop working soon.
2019-02-25 11:00:57 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.sonoff.sensor. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 962, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.sonoff.sensor'; 'custom_components.sonoff' is not a package
2019-02-25 11:00:57 ERROR (MainThread) [homeassistant.loader] Unable to find platform sonoff
2019-02-25 11:00:57 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform sonoff.sensor: Platform not found.
2019-02-25 11:00:57 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback <function EventBus.async_listen_once.<locals>.onetime_listener at 0x72fd1618>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 64, in uvloop.loop.Handle._run
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 626, in onetime_listener
    self._hass.async_run_job(listener, event)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 333, in async_run_job
    target(*args)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/person/__init__.py", line 342, in person_start_hass
    self.person_updated()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/person/__init__.py", line 363, in person_updated
    self._update_state()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/person/__init__.py", line 374, in _update_state
    for entity_id in self._config.get(CONF_DEVICE_TRACKERS, []):
TypeError: 'NoneType' object is not iterable
2019-02-25 11:01:03 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.sonoff.switch. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 962, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.sonoff.switch'; 'custom_components.sonoff' is not a package
2019-02-25 11:01:03 WARNING (MainThread) [homeassistant.loader] Integrations need to be in their own folder. Change switch/sonoff.py to sonoff/switch.py. This will stop working soon.
2019-02-25 11:01:04 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.sonoff.switch. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 962, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.sonoff.switch'; 'custom_components.sonoff' is not a package
2019-02-25 11:01:04 WARNING (MainThread) [homeassistant.loader] Integrations need to be in their own folder. Change switch/sonoff.py to sonoff/switch.py. This will stop working soon.
2019-02-25 11:01:16 ERROR (SyncWorker_18) [homeassistant.components.xiaomi_aqara] No gateway discovered
2019-02-25 11:01:16 ERROR (MainThread) [homeassistant.setup] Setup failed for xiaomi_aqara: Component failed to initialize.

**Comment by smartHomeHub** [comment]
Actually, there are a lot of errors. About smartir there is an error in your temperature_sensor:
`Temperature is not a number: {}".format(temperature))`
Please remove `temperature_sensor: sensor.living_room_temperature` and  `humidity_sensor: sensor.living_room_humidity` from your config and tell me the results

**Comment by ginko64** [comment]
Actually I do not have any temperature_sensor installed! There was a Badge on the top of the UI by default. I provide to delete it and all the sonoff that cause many errors too.

This is the new log:

019-02-25 11:20:23 WARNING (MainThread) [homeassistant.loader] You are using a custom component for smartir.climate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-02-25 11:20:23 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 352, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 239, in async_update_ha_state
    attr = self.state_attributes or {}
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/climate/__init__.py", line 234, in state_attributes
    self.precision),
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/temperature.py", line 22, in display_temp
    "Temperature is not a number: {}".format(temperature))
TypeError: Temperature is not a number: 25
2019-02-25 11:20:24 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback <function EventBus.async_listen_once.<locals>.onetime_listener at 0x75290a08>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 64, in uvloop.loop.Handle._run
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 626, in onetime_listener
    self._hass.async_run_job(listener, event)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 333, in async_run_job
    target(*args)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/person/__init__.py", line 342, in person_start_hass
    self.person_updated()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/person/__init__.py", line 363, in person_updated
    self._update_state()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/person/__init__.py", line 374, in _update_state
    for entity_id in self._config.get(CONF_DEVICE_TRACKERS, []):
TypeError: 'NoneType' object is not iterable
2019-02-25 11:20:45 ERROR (SyncWorker_2) [homeassistant.components.xiaomi_aqara] No gateway discovered
2019-02-25 11:20:45 ERROR (MainThread) [homeassistant.setup] Setup failed for xiaomi_aqara: Component failed to initialize.

**Comment by ginko64** [comment]
and this is my configurator.yaml no sensor declared:

**Comment by ginko64** [comment]
and this all the entities I have. (only weather card installed)

**Comment by ginko64** [comment]
Here are other info about the log.
Seems there is something missing in folder usr/local/lib/pyton3.7 but I do not have that folder in my Hassio but only pyton3.6

Here are some screenshot:

**Comment by ekkesa** [comment]
I removed everything and reinstalled it - that seemed to have resolved it - The climate component is now working. I have not yet added the media_player component back yet.
