### ISSUE TITLE
stopped working, no errors

### ISSUE THREAD

**Issue by Kedryn** [smartHomeHub/SmartIR#1232]
Mi smartir stopped working. I'm not sure when, but recently it is doing nothing when i give commands via HA buttons or calling services

there is no error in logs
if i call the send command, it returns ok, but my RM3 does nothing

the device itself is working because i can command my tv and my hi fi from the phone app and via google voice commands
but not from HA

it *can* be since last HA update, the march one, but i'm not sure.

**Comment by tayanov** [comment]
+1
if i send manualy command via service, AC is work fine. But smarir nope

**Comment by Kedryn** [comment]
``For me it does NOT work via Home assistant, but it works via smartphone app

I've found this in the debug log:

```2024-05-31 13:46:13.584 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities remote.irsalotto_remote are missing or not currently available
2024-05-31 13:46:54.450 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching IRSalotto (RM mini 3 at 192.168.0.187) data: [Errno -4000] Network timeout: No response received within 5s```

and also this:

```2024-05-31 13:45:36.158 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140701838032448] Error handling message: Unknown error (unknown_error) Marco from 194.183.80.98 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/broadlink/remote.py", line 150, in _extract_codes
    codes = self._codes[device][cmd]
            ~~~~~~~~~~~^^^^^^^^
KeyError: 'tv_salotto'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 793, in handle_execute_script
    script_result = await script_obj.async_run(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1731, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 503, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 533, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 501, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 736, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 699, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/broadlink/remote.py", line 227, in async_send_command
    code_list = self._extract_codes(commands, subdevice)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/broadlink/remote.py", line 152, in _extract_codes
    raise ValueError(f"Command not found: {repr(cmd)}") from err```

The media_player.tv_salotto is configured like this:

```media_player:
  - platform: smartir
    name: TV Salotto
    unique_id: tv_salotto
    device_code: 1040
    controller_data: remote.irsalotto_remote #192.168.0.187
    power_sensor: binary_sensor.stato_televisione```
    
  and the 1040.json is this:
  
  
```{
    "manufacturer": "LG",
    "supportedModels": [
      "22MT47DC"
    ],
    "supportedController": "Broadlink",
    "commandsEncoding": "Base64",
    "commands": {
        "off": "JgBoAAABKZUSExEUETgSExITEhMSExEUEjgROREUETkRORE5ETkSNxMSExISExM3EhMSExITERQSOBE5ETkRFBI4EjgSOBE4EgAFLQABKUsRAAxkAAEnTBIADGMAASlLEgAMYwABKEwSAA0F",
        "on": "JgBoAAABKZUSExEUETgSExITEhMSExEUEjgROREUETkRORE5ETkSNxMSExISExM3EhMSExITERQSOBE5ETkRFBI4EjgSOBE4EgAFLQABKUsRAAxkAAEnTBIADGMAASlLEgAMYwABKEwSAA0F",
        "previousChannel": "JgBgAAABK5MTEhMSEzcTEhMSExITEhMSEzcTNhQSEzYUNhQ2FDYUNhQ2ExITEhMSExITEhMSExITEhM3EzcTNhQ2FDYUNhQ2FAAFKwABK0kTAAxjAAErSRMADGIAAStJEwANBQAAAAAAAAAA",
        "nextChannel": "JgBgAAABK5MTEhMSEzYUEhMRFBEUERQRFDYUNhQRFDYTNxM3EzcTNxMSExITEhMSExITEhMSExITNhQ2FDYUNhQ2EzcTNxM3EwAFLAABKkkTAAxjAAEqSRQADGIAASpJEwANBQAAAAAAAAAA",
        "volumeDown": "JgBgAAABK5IUERQRFDYUERMSExITEhMSEzcTNxMSEzcTNxM3EzgSNxM2FDYUERQRFBEUERQRFBEUERQREzcTOBI3EzcTNxM3EwAFLQABKUkUAAxiAAErSRMADGMAAStIFAANBQAAAAAAAAAA",
        "volumeUp": "JgBgAAABK5IUEhMRFDYUERQRFBEUERQRFDYTNxMSEzcTNxM3EzcTNxMSEzcTEhMSExITEhMSExITNxMSEzYUNhQ2FDYTNxM3EwAFLAABK0kTAAxjAAErSBQADGIAAStJEwANBQAAAAAAAAAA",
        "mute": "JgBgAAABK5MTEhMSEzcTEhMSExITEhMSEzcTNxMSEzYUNhQ2FDYUNRU2FBEUERQ2ExITEhMSExITEhM3EzcTEhM3EzYUNhQ2FAAFKwABK0kTAAxjAAEqShMADGMAASpJFAANBQAAAAAAAAAA",
        "sources": {
            "Channel 0": "JgBoAAABJ5YRFBEUETkRFBEUEhMSExITETgTNxITEjgSOBI4ETkRORITERQRFBEUETgSExITERQSOBE5ETkRORITETkQORI4EQAFLQABKUsRAAxjAAEpShIADGIAASpKEQAMYwABKUoSAA0F",
            "Channel 1": "JgBIAAABKZUSExEUETgSExEVEBUQFRAVEDkRORITEjgRORI4ETkROBM3EhMSExITETkRFBEVEBUQFBE5ETkRORITETkRORE5EQANBQ==",
            "Channel 2": "JgBgAAABKZURExITEjgSExEUEhMRFBEUEjgROREUEjgTNxI4EjgROBITEjgSExEUETkSExEUERQROREUETkROREUETgSOBI4EgAFLQABKEsSAAxjAAEoSxEADGMAASlLEgANBQAAAAAAAAAA",
            "Channel 3": "JgBoAAABKJUTEhITETkRFBEUEhMSExEUETkROREUETkRORI3EjgSOBI4EjgRFBEUETkRFBEUERQRFBEUETgTNxITETkRORI4EQAFLQABKUsRAAxjAAEoSxIADGMAAShLEgAMYwABJ0wSAA0F",
            "Channel 4": "JgBYAAABKJURFBEUETkRFBEUERQSExEUETkROBMSEjgSOBI4ETkSOBEUERQROREUETgSExITEhMRORI4ERQRORITETkSOBE4EgAFLQABKEsRAAxjAAEpSxEADQU=",
            "Channel 5": "JgBgAAABKJURFBITEjgRFBEUERQRFBEUETgTNxITETkRORE5ETkSOBE5EhMROBITEjgRFBITEhMRFRA5ERQRORITETkSOBE5EQAFLQABKEsRAAxjAAEpSxIADGIAASlLEQANBQAAAAAAAAAA",
            "Channel 6": "JgBgAAABKJYRFBETEjgSExEUERQRFBEUETgTOBEUETkRORE5ETgTNxITEjgRORITEjgRFBITERQSOBEUEhMROREUETgSOBI4EQAFLgABKEsSAAxjAAEoSxEADGQAAShLEQANBQAAAAAAAAAA",
            "Channel 7": "JgBoAAABKZURExMSEjgSFBAUExIRFBEVEDkRORITETkRORE4EjgTNxE5EjgROREUETkRFRETERQRFBEUERQROBITEjgSOBI4EQAFLQABKUsSAAxiAAEoSxIADGMAAShLEwAMYgABKEsRAA0F",
            "Channel 8": "JgBgAAABKJURFBITETkSExEUERQSExEUETgSOBITEjgSOBI4EjgROREUEhMRExI4EjgSExEUEhMSOBI4ETkRFBEUETgSOBI4EgAFLQABKEsRAAxkAAEoSxIADGIAASlLEQANBQAAAAAAAAAA",
            "Channel 9": "JgBoAAABKJURFBITETkRFBEUERQRFBITETkROREUETgSOBE5ETkSOBE5ERQSExE5ETgSFBETEhMSExE5EjgRFBEUETkSOBE4EgAFLQABKEsRAAxjAAEoSxIADGMAASdMEgAMYgABKUoSAA0F",
            "Input": "JgBIAAABIZMUEBISEzYUERISExITEhISEzYUNRQREjcVOREzFTQTNhQ1EzYVEBI3FRASEhMSEhITEhISEzYTEhI3FTQTNhM2EwANBQ=="
        }
    }
}```

But the above error states that: "ValueError: Command not found: 'off'"

**Comment by Kedryn** [comment]
Completed?
