### ISSUE TITLE
check_updates = conf[CONF_CHECK_UPDATES] NoneType error

### ISSUE THREAD

**Issue by P2mb2** [smartHomeHub/SmartIR#131]
Hi, 

when i start HA, i get this error on logs. Any clue?

`2019-05-26 12:01:32 INFO (MainThread) [homeassistant.setup] Setting up smartir
2019-05-26 12:01:32 ERROR (MainThread) [homeassistant.setup] Error during setup of component smartir
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 153, in _async_setup_component
    hass, processed_config)
  File "/config/custom_components/smartir/__init__.py", line 43, in async_setup
    check_updates = conf[CONF_CHECK_UPDATES]
TypeError: 'NoneType' object is not subscriptable
`

My config 
`climate:
  - platform: smartir
    name: Office AC
    unique_id: office_ac
    device_code: 1380
    controller_data: 192.168.1.xxx

switch:
    - platform: broadlink
    host: 192.168.1.xxx
    mac: xxxx

**Comment by P2mb2** [comment]
My bad.. 

I forgot to add smartir: root configuration on yaml file.
