### ISSUE TITLE
How to turn off my projector BenqGP20

### ISSUE THREAD

**Issue by fr00kt** [smartHomeHub/SmartIR#139]
How to turn off my projector, if you want to turn it off, you need to press the power button twice?

**Comment by smartHomeHub** [comment]
Please add the off command twice as an array in the JSON file.

**Comment by fr00kt** [comment]
like this?
```
"commands": {
        "off": [
            "nMwnEwlk0mk5mEsmoBBAB+AH4AfgB+AH4AfzGbA0MARAAfgU+AH4AfgB+Bx4OfgEeAR4BDzCAA==",
           "nMwnEwlk0mk5mEsmoBBAB+AH4AfgB+AH4AfzGbA0MARAAfgU+AH4AfgB+Bx4OfgEeAR4BDzCAA=="
        ],
        "on": "nMwnEwlk0mk5mEsmoBBAB+AH4AfgB+AH4AfzGbA0MARAAfgU+AH4AfgB+Bx4OfgEeAR4BDzCAA=="
```
I tried:
```
2019-06-11 12:50:21 ERROR (MainThread) [custom_components.smartir.media_player] can only concatenate str (not "list") to str
Traceback (most recent call last):
  File "/config/custom_components/smartir/media_player.py", line 249, in send_command
    await self._controller.send(command)
  File "/config/custom_components/smartir/controller.py", line 88, in send
    'command':  self._encoding.lower() + ':' + command
TypeError: can only concatenate str (not "list") to str

```

**Comment by smartHomeHub** [comment]
Broadlink or Xiaomi controller?

**Comment by fr00kt** [comment]
Xiaomi

**Comment by smartHomeHub** [comment]
It will not work for the Xiaomi controller. Alternatively, you can find the pronto commands of your device and add the number of repeats at the end of each command.

https://www.home-assistant.io/components/remote.xiaomi_miio/#command-types

**Comment by fr00kt** [comment]
Please tell me how to write
like this?
```
    "supportedController": "Xiaomi",
    "commandsEncoding": "Pronto",
    "commands": {
        "off": "0000 006C 0000 0022 015B 00AD 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0041 0016 0016 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0016 0016 0041 0016 0041 0016 0016 0016 0016 0016 0016 0016 0041 0016 0041 0016 0016 0016 0016 0016 0016 0016 0041 0016 0041 0016 0041 0016 0016 0016 0016 0016 0041 0016 0041 0016 0041 0016 05F7:2",
        "on": "0000 006C 0000 0022 015B 00AD 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0041 0016 0016 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0016 0016 0041 0016 0041 0016 0016 0016 0016 0016 0016 0016 0041 0016 0041 0016 0016 0016 0016 0016 0016 0016 0041 0016 0041 0016 0041 0016 0016 0016 0016 0016 0041 0016 0041 0016 0041 0016 05F7"
    }
```

**Comment by smartHomeHub** [comment]
Exactly

**Comment by fr00kt** [comment]
When I use the raw commands, the LED on the controller flashes, and when I use Pronto, there is no reaction

**Comment by mSapik** [comment]
Hello. How can i convert command from broadlink hex to base64, for my xiaomi controller?
Will you add support Mitsubishi AC for xiaomi controller?
Thanks. Sorry for bad english/
