### ISSUE TITLE
Fan-component: Error while setting up platform smartir

### ISSUE THREAD

**Issue by Fabenissimo** [smartHomeHub/SmartIR#161]
*Home Assistant version**
 0.95.0

**SmartIR version** 
latest

**SmartIR configuration**
```
smartir:
```

yaml
```
fan:
  - platform: smartir
    name: Ventilator Zimmer Fabian
    unique_id: vent_room_fabian
    device_code: 9943
    controller_data: 192.168.2.53
```

**Describe the bug**
Component not loading after HA restart, climate component on the other hand works perfectly.

**Debug log**
```
2019-07-05 16:43:13 ERROR (MainThread) [homeassistant.components.fan] Error while setting up platform smartir
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/home/homeassistant/.homeassistant/custom_components/smartir/fan.py", line 76, in async_setup_platform
    hass, config, device_data
  File "/home/homeassistant/.homeassistant/custom_components/smartir/fan.py", line 92, in __init__
    self._speed_list = [SPEED_OFF] + device_data['speed']
KeyError: 'speed'
```

**Additional context**
My fan json-file: (created via the webapplication you linked in your github, located under .../custom_components/smartir/codes/fan/9943.json)
```
{"manufacturer":"Delonghi","supportedModels":["PAC N77 Eco"],"supportedController":"Broadlink","commandsEncoding":"Base64","speeds":["level1","level2","level3"],"commands":{"off":"JgBIAAABKZMSExISEhIRNxMREhISNxMRERMRExI2EhISNxMRERMSEhI2EhMRExESEhITEhISEhIRExISEhISNxMREhIRExISEgANBQ==","forward":{"level1":"JgBIAAABKZMSEhMSEhISNhISEhISNhMSEhIRNxMREhISNxMRERMSEhISEjYTNRMREhMSEhISEjcSERISEhITNhMRERQREhISEgANBQ==","level2":"JgBIAAABKpISEhQREhISNxMRERISNxMREhIRFBE2ExETNhMRERMSEhISEjYTNhISEhISEhISEjcTERETERMSNhISEhMRExESEgANBQ==","level3":"JgBIAAABKpISEhMSEhISNhMSERISNxMREhIRExISEjYSNxMRERMSEhISEjYUMhYRERMSEhISEjcTERESEhITNhMREhMRExESEgANBQ=="}}}
```

I'm sorry if I missed something when creating this issue here. First timer. 

As I said, my climate-configuration works just fine. Uses the same broadlink switch.

**Comment by smartHomeHub** [comment]
There is a syntax error in your JSON file. It is speed and not speeds. Please try the attached file.

[9943.zip](https://github.com/smartHomeHub/SmartIR/files/3389320/9943.zip)

**Comment by Fabenissimo** [comment]
Ok, thank you for investigating. After a HA restart my fan-component loads without errors. Now, when I try to Turn on the fan I get a new error:

`
'default'
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 121, in handle_call_service
    connection.context(msg))
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1150, in async_call
    self._execute_service(handler, service_call))
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1172, in _execute_service
    await handler.func(service_call)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_component.py", line 194, in handle_service
    required_features
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 316, in entity_service_call
    future.result()  # pop exception if have
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 337, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/home/homeassistant/.homeassistant/custom_components/smartir/fan.py", line 224, in async_turn_on
    await self.async_set_speed(speed)
  File "/home/homeassistant/.homeassistant/custom_components/smartir/fan.py", line 207, in async_set_speed
    await self.send_command()
  File "/home/homeassistant/.homeassistant/custom_components/smartir/fan.py", line 239, in send_command
    command = self._commands[direction][speed]
KeyError: 'default'
`

Maybe I should add that I created this file with the web-app you had linked in you GitHub.

**Comment by smartHomeHub** [comment]
Please try the new attached file
[9943.zip](https://github.com/smartHomeHub/SmartIR/files/3389834/9943.zip)

**Comment by Fabenissimo** [comment]
Perfect. That did it. Seems like this json file generator doesn't fully work for fans. Thanks anyway.
