### ISSUE TITLE
I Did all configuration but I can not see the component

### ISSUE THREAD

**Issue by ginko64** [smartHomeHub/SmartIR#20]
Hi there,
I added all the folders and files in the custom_components following your guide. (I checked several times if it is all right). Created the json file and put it in the codes/climate.
This is my configuration.yaml:

`switch:
  - platform: broadlink
    host: 192.168.1.44
    mac: '02:0F:B5:21:A6:7C'  
  
climate:
  - platform: smartir
    name: Condizionatore
    device_code: 4402
    controller_send_service: switch.broadlink_send_packet_192_168_1_44`

I do not see any errors in the log, but the component is not showing up. 
I can not find the component under Developer Tools->States.
What do I wrong?
Thanks in advance
Mario

**Comment by smartHomeHub** [comment]
Hi Mario,
I’m afraid I can’t help you without any error in logs

**Comment by ginko64** [comment]
Here are other info about the log.
Seems there is something missing in folder usr/local/lib/pyton3.7 but I do not have that folder in my Hassio but only pyton3.6

Here are some screenshot:
<img width="1071" alt="schermata 2019-02-25 alle 12 58 20" src="https://user-images.githubusercontent.com/6617849/53341813-d6581b80-390c-11e9-9804-49f6adcfd018.png">
<img width="309" alt="schermata 2019-02-25 alle 12 59 31" src="https://user-images.githubusercontent.com/6617849/53341830-e3750a80-390c-11e9-9874-44b4d7c3642e.png">

**Comment by ginko64** [comment]
Actually I do not have any temperature_sensor installed! There was a Badge on the top of the UI by default. I provide to delete it and all the sonoff that cause many errors too.

This is the new log:

019-02-25 11:20:23 WARNING (MainThread) [homeassistant.loader] You are using a custom component for smartir.climate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-02-25 11:20:23 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 352, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 239, in async_update_ha_state
    attr = self.state_attributes or {}
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/climate/__init__.py", line 234, in state_attributes
    self.precision),
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/temperature.py", line 22, in display_temp
    "Temperature is not a number: {}".format(temperature))
TypeError: Temperature is not a number: 25
2019-02-25 11:20:24 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback <function EventBus.async_listen_once.<locals>.onetime_listener at 0x75290a08>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 64, in uvloop.loop.Handle._run
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 626, in onetime_listener
    self._hass.async_run_job(listener, event)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 333, in async_run_job
    target(*args)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/person/__init__.py", line 342, in person_start_hass
    self.person_updated()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/person/__init__.py", line 363, in person_updated
    self._update_state()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/person/__init__.py", line 374, in _update_state
    for entity_id in self._config.get(CONF_DEVICE_TRACKERS, []):
TypeError: 'NoneType' object is not iterable
2019-02-25 11:20:45 ERROR (SyncWorker_2) [homeassistant.components.xiaomi_aqara] No gateway discovered
2019-02-25 11:20:45 ERROR (MainThread) [homeassistant.setup] Setup failed for xiaomi_aqara: Component failed to initialize.

**Comment by ginko64** [comment]
> Hi Mario,
> I’m afraid I can’t help you without any error in logs

I post the logs over here.

Can you help me please? 

Thanks

**Comment by smartHomeHub** [comment]
What is the version of HA?

**Comment by ginko64** [comment]
> What is the version of HA?

the last one installed brand new 3 hours ago 0.88.1

**Comment by smartHomeHub** [comment]
Please try with the minimum config:
```
switch:
  platform: broadlink
  host: 192.168.1.44
  mac: '02:0F:B5:21:A6:7C'
  timeout: 30
  friendly_name: "Attuatore Broadlink"
  type: rm
  
smartir:

climate:
  platform: smartir
  name: Climatizzatore
  device_code: 1010
  controller_send_service: switch.broadlink_send_packet_192_168_1_44

```

**Comment by ginko64** [comment]
Ok I try this evening and let you know.

Thanks again for the help

**Comment by ginko64** [comment]
> Please try with the minimum config:
> 
> ```
> switch:
>   platform: broadlink
>   host: 192.168.1.44
>   mac: '02:0F:B5:21:A6:7C'
>   timeout: 30
>   friendly_name: "Attuatore Broadlink"
>   type: rm
>   
> smartir:
> 
> climate:
>   platform: smartir
>   name: Climatizzatore
>   device_code: 1010
>   controller_send_service: switch.broadlink_send_packet_192_168_1_44
> ```

Try as you say but nothing change. The component doesn't show up and I have no entity in my state on Hassio.
I choose the path for the custom_components/smartir… directory --> inside the /config folder, the same folder of the configuration.yaml is this correct?
Any other ideas?

**Comment by smartHomeHub** [comment]
Yes. The path is correct. Does the same errors in the log?

**Comment by ginko64** [comment]
Here is the full log:

> 
2019-02-26 21:04:15 WARNING (MainThread) [homeassistant.loader] You are using a custom component for smartir which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-02-26 21:04:19 WARNING (MainThread) [homeassistant.loader] You are using a custom component for smartir.climate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-02-26 21:04:19 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 352, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 239, in async_update_ha_state
    attr = self.state_attributes or {}
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/climate/__init__.py", line 234, in state_attributes
    self.precision),
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/temperature.py", line 22, in display_temp
    "Temperature is not a number: {}".format(temperature))
TypeError: Temperature is not a number: 25
2019-02-26 21:04:20 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback <function EventBus.async_listen_once.<locals>.onetime_listener at 0x74c99fa8>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 64, in uvloop.loop.Handle._run
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 626, in onetime_listener
    self._hass.async_run_job(listener, event)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 333, in async_run_job
    target(*args)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/person/__init__.py", line 342, in person_start_hass
    self.person_updated()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/person/__init__.py", line 363, in person_updated
    self._update_state()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/person/__init__.py", line 374, in _update_state
    for entity_id in self._config.get(CONF_DEVICE_TRACKERS, []):
TypeError: 'NoneType' object is not iterable
2019-02-26 21:04:43 ERROR (SyncWorker_6) [homeassistant.components.xiaomi_aqara] No gateway discovered
2019-02-26 21:04:43 ERROR (MainThread) [homeassistant.setup] Setup failed for xiaomi_aqara: Component failed to initialize.

**Comment by smartHomeHub** [comment]
I’m really don’t know. Could you zip and send me your whole configuration.yaml file?

**Comment by ginko64** [comment]
> I’m really don’t know. Could you zip and send me your whole configuration.yaml file?

no problem it is ready to send to you. please write me here ginkorege@gmail.com so I do not share it in here.
Thanks
