### ISSUE TITLE
Error, component climate not loading after update

### ISSUE THREAD

**Issue by acidquest** [smartHomeHub/SmartIR#21]
02-24 23:23:34 ERROR (MainThread) [homeassistant.components.climate] Error while setting up platform smartir
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/home/acidquest/.homeassistant/custom_components/smartir/climate.py", line 103, in async_setup_platform
    temperature_sensor, humidity_sensor, power_sensor
  File "/home/acidquest/.homeassistant/custom_components/smartir/climate.py", line 121, in __init__
    self._commands_encoding = device_data['commandsEncoding']
KeyError: 'commandsEncoding'

**Comment by acidquest** [comment]
x86_64
dev	false
docker	false
hassio	false
os_name	Linux
python_version	3.6.7
timezone	Europe/Moscow
version	0.88.1
virtualenv	false
Lovelace
mode	yaml
resources	3
views	4

**Comment by smartHomeHub** [comment]
Please zip your Json file and upload it here

**Comment by acidquest** [comment]
I find new line in config: commands_encoding: Base64. I add this and all work fine. Sorry. Please close issue
