### ISSUE TITLE
Platform error climate.smartir - cannot import name 'STATE_HEAT' 

### ISSUE THREAD

**Issue by itayraviv** [smartHomeHub/SmartIR#244]
**Home Assistant version**
0.99.3

**SmartIR version**
1.7.3 - Installed with HACS manually (as "Integration"):  
**SmartIR configuration**
smartir:
  update_branch: rc
climate:
  - platform: smartir
    name: play_room_aircon
    device_code: 1180
    controller_data: 10.0.0.62
    temperature_sensor: sensor.temperature
    humidity_sensor: sensor.humidity
    power_sensor: binary_sensor.ac_power

**Describe the bug**
Trying to see the "climate.XXX" entity in my HA entity list, many versions ago it worked (0.8somthing i think).
I saw a similar issue, what solved the guy issue was deleting the cache and downloading the rc and not master branches files - I deleted every file under "custom_components/smartir/" and downloaded both rc/master branches and same got same error.

**Debug log**
2019-10-23 00:56:53 ERROR (MainThread) [homeassistant.config] Platform error: climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 757, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 232, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/smartir_orig/climate.py", line 9, in <module>
    from homeassistant.components.climate.const import (
ImportError: cannot import name 'STATE_HEAT' from 'homeassistant.components.climate.const' (/usr/src/homeassistant/homeassistant/components/climate/const.py)
2019-10-23 00:56:53 INFO (MainThread) [homeassistant.setup] Setting up climate
2019-10-23 00:56:53 INFO (MainThread) [homeassistant.setup] Setup of domain climate took 0.0 seconds.
2019-10-23 00:56:53 INFO (MainThread) [homeassistant.setup] Setting up group
2019-10-23 00:56:53 INFO (MainThread) [homeassistant.setup] Setting up smartir
2019-10-23 00:56:54 ERROR (MainThread) [custom_components.smartir_orig] Invalid response from the server while checking for a new version
2019-10-23 00:56:54 INFO (MainThread) [homeassistant.setup] Setup of domain smartir took 0.6 seconds.

I have "switch:" imported as well of course:
  - platform: broadlink
    host: 10.0.0.62
    mac: 'XX:XX:XX:XX:XX:XX'
    type: rm_mini
    timeout: 15
    friendly_name: br_mini_playroom
    switches:
      playroom_ac_power:
        friendly_name: "Power"
        command_on: 'JgCSAAABKZMWNhYSFhEXNRYSFjYWNhYRFjYWEhY2FhEWEhYSFhEWEhYTFhEWEhYSFhEWNhY2FhIWERYSFhIWERY2FhIWNhYRFxEWNhYSFgACkBY2FhIWERcRFhIWERcRFhIWERcRFhIWERcRFhIWERcRFhIWERcRFhIWERcRFhIWERcRFhIWERcRFhIWERcRFjYWAA0FAAAAAAAA'
        command_off: 'JgCSAAABKpIXNRcRFxAYEBcRFzUXNBgQFxEXNRc0GBAXERcQGBAXERcQGBAXERcQGBAXNRcRFxAXERcRFxAXERc1FxAYNBgQFxEXNBgQFwACjxg0GBAXERcQGBAXERcQGBAXERcQGBAXERcQGBAXERcQGBAXERcQGBAXERcQGBAXERcQGBAXERcQGDQXERcQGBAXAA0FAAAAAAAA'

After all that, I see sensors and switches entities but no "climate.XX" entity which i want to add a "dual-thermostat"

Anyone can assist please?
Thanks !

**Comment by smartHomeHub** [comment]
Is SmartIR installed in /custom_components/smartir_orig/ ?

**Comment by itayraviv** [comment]
oohhh... 
that is an old smartir (before update/hacs), i have the 1.7.3 (latest) files at:
/home/pi/docker/homeassistant/custom_components/smartir
why it is looking for climate.py at "smartir_orig"? where i change the path?

**Comment by smartHomeHub** [comment]
I suggest you remove all SmartIR related folders and start over. You also need to consider how to install SmartIR. Don't mix HACS and custom install.

**Comment by itayraviv** [comment]
ok, will try and report back in a few minutes...
thanks

**Comment by itayraviv** [comment]
it worked... deleted everything.... reinstalled from HACS and all works ! thanks !
closing issue.

**Comment by smartHomeHub** [comment]
Because you are using HACS I also recommend disabling the built-in SmartIR updater from config as follows:

```
smartir:
  check_updates: false
```
