### ISSUE TITLE
ERROR (MainThread) [homeassistant.components.broadlink] Failed to connect to device

### ISSUE THREAD

**Issue by chemelli74** [smartHomeHub/SmartIR#250]
**Home Assistant version** 0.101.3

**SmartIR version** 1.7.3

**SmartIR configuration** 

smartir:

switch:
  - platform: broadlink
    host: 192.168.1.11
    mac: '24:df:a7:36:76:6e'

climate:
  - platform: smartir
    name: Condizionatore Salotto
    unique_id: salotto_ac
    device_code: 1121
    controller_data: 192.168.1.11
    temperature_sensor: sensor.temperature
    humidity_sensor: sensor.humidity
    power_sensor: binary_sensor.ac_power

fan:
  - platform: smartir
    name: Ventola Cucina
    unique_id: cucina_fan
    device_code: 1000
    controller_data: 192.168.1.11
    power_sensor: binary_sensor.fan_power

```yaml

Add configuration here

```

**Describe the bug** cannot connect to device, tested even with "broadlink.learn"

**Debug log**

2019-11-12 12:20:37 ERROR (MainThread) [homeassistant.components.broadlink] Failed to connect to device

Add your logs here.

```

**Additional context**

Add any other context about the problem here.

**Comment by chemelli74** [comment]
Anyone on that ?

Thank you,

Simone

**Comment by smartHomeHub** [comment]
It looks like a problem on your Broadlink and not on SmartIR

**Comment by chemelli74** [comment]
Hi @smartHomeHub, device works fine with both IHC for EU and Broadlink apps.
Is just with SmartIR that it doesn't work.
Is there a way to get more debug and analyze the issue ?

Thx,

Simone

**Comment by smartHomeHub** [comment]
SmartIR is using the broadlink.send service. Could you try if the service sends commands to your broadlink device?

![image](https://user-images.githubusercontent.com/47714957/69962551-f0b3cb00-1516-11ea-8581-b42879a0be49.png)

**Comment by chemelli74** [comment]
> SmartIR is using the broadlink.send service. Could you try if the service sends commands to your broadlink device?

Nope, it doesn't. Same error in log: Failed to connect to device

**Comment by macbisho** [comment]
Not sure why this is still(?) marked as closed.

Simone still has problems, and I am seeing the exact same issue when I try to call the service with broadlink.send

I've got two different devices - both working perfectly fine through the Broadlink app, both showing in my UniFi as connected with proper IP addresses.

Neither of them are responding - same error as above 

`'192.168.0.51'
Traceback (most recent call last):
  File "/Users/admin/homeassistant/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/Users/admin/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1234, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/Users/admin/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1259, in _execute_service
    await handler.func(service_call)
  File "/Users/admin/homeassistant/lib/python3.7/site-packages/homeassistant/components/broadlink/__init__.py", line 48, in _learn_command
    device = hass.data[DOMAIN][call.data[CONF_HOST]]
KeyError: '192.168.0.51'`


`'192.168.0.31'
Traceback (most recent call last):
  File "/Users/admin/homeassistant/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/Users/admin/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1234, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/Users/admin/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1259, in _execute_service
    await handler.func(service_call)
  File "/Users/admin/homeassistant/lib/python3.7/site-packages/homeassistant/components/broadlink/__init__.py", line 48, in _learn_command
    device = hass.data[DOMAIN][call.data[CONF_HOST]]
KeyError: '192.168.0.31'`
