### ISSUE TITLE
Failed to call service fan/turn_on. 'default'

### ISSUE THREAD

**Issue by mshuflin** [smartHomeHub/SmartIR#303]
**Home Assistant version**
0.107.5
**SmartIR version**
1.7.4
**SmartIR configuration**

**json file**
`{
  "manufacturer": "KDK",
  "supportedModels": [
    "K14Y5",
    "K14X5"
  ],
  "supportedController": "Broadlink",
  "commandsEncoding": "Base64",
  "speed": [
    "low",
    "medium",
    "high"
  ],
  "commands": {
    "off": "JgDwAGw5Dw0QKRANDw0PDQ8NEA0PDQ8NEA0PDQ8NDw4PKRANDw0PDRANDw0PDRApDw0QKRApDw0PDg8pDw4PDQ8NDw4PKRANDw0PDQ8ODykQKQ8NEA0PKRANDw0PDg8pECkPDQ8ODykQDQ8pEA0PKRANDyoPDQ8AAaIIAAfhczcPDg8pEA0PDQ8NEA0PDQ8NEA0PDQ8NEA0PDQ8qDw0PDg8NDw0PDg8NDyoPDQ8qDykQDQ8NDyoPDQ8ODw0PDQ8qDw0QDQ8NDw0QKQ8qDw0PDg8pEA0PDQ8NECkPKg8NEA0PKRANDyoODg8qDw0PKg8NDwANBQAAAAAAAAAA",
    "forward": {
      "low": "JgDsAHI4Dw0PKg8NDw0QDQ8NEAwQDQ8NDw0QDQ8NDw0QKRAMEA0PDQ8NEA0PDQ8qDw0PKg8qDw0PDRApDw0QDQ8NDw0QKQ8NEA0PDQ8NECkQKQ8NDw4PKRANDw0PDRANDykQDQ8NDyoPDQ8qDw0PDg8NDyoPDQ8ACYtzOA8NDyoPDRANDw0PDRANDw0PDQ8ODw0PDQ8NECkQDQ8NDw0QDBANDw0PKg8NECkPKg8NDw0QKRANDw0PDRANDykQDQ8NDw0QDQ8pECkPDRANDykQDQ8NEA0PDQ8qDw0PDRApDw0QKQ8NEA0PDQ8qDw0QAA0FAAAAAAAAAAAAAAAA",
      "medium": "JgDwAG05Dw0PKg4ODw0QDQ8NDw0QDQ8NDw0QDQ8NDw0PKg8NDw4PDQ8NEA0PDQ8qDw0PKg8pEA0PDQ8qDw0PDg8NDw0PKg8NDw4PDQ8NDyoPKg8NDw0PDg8pEA0PDQ8NECkPDRANDw0PKg8qDw0PDRANDykQDQ8ACYtzNw8ODykQDQ8NDw0PDg4ODw0PDg8NDw0PDg8NDyoPDQ8NDw4PDQ8NDw0QKQ8ODykQKQ8NEA0PKRANDw0PDRANDykQDQ8NDw0QDQ8qDykQDQ8NDw0QKQ8NDw4PDQ8qDw0PDg8NDyoPKRANDw0PDg8pEA0PAAhgBQANBQAAAAAAAAAA",
      "high": "JgDsAHI4Dw0PKg8NDw4PDQ8NDw0QDQ8NDw0QDQ8NDw0QKQ4OEA0PDQ8NEA0PDQ8qDw0PKg8qDw0PDRApDg4QDQ8NDw0QKQ8NEA0PDQ8NECkOKw4ODw4PKQ8qDw0QDQ8NDyoODg8NECkPKg8qDw0PDQ8ODykPDg8ACYtzNw8ODykQDQ8NDw0PDg8NDw0PDg8NDw0PDg8NDyoPDQ8NDw4PDQ8NDw4PKQ8ODykPKg8NEA0PKRANDw0PDRANDykQDQ8NDw0QDQ8qDykPDg8NDyoPKQ8ODw0PDRApDg8PDQ8qDykQKQ8ODg4PDQ8qDw0QAA0FAAAAAAAAAAAAAAAA"
    }
  }
}`

`# Living Room Fan
  - platform: smartir
    name: Living Room Fan
    unique_id: living_room_fan
    device_code: 2000
    controller_data: 192.168.0.33`

Add configuration here

**Lovelace card**
`      - entity: fan.living_room_fan
        hold_action:
          action: more-info
        show_icon: true
        show_name: true
        tap_action:
          action: toggle
        theme: Backend-selected
        type: button
`

**Describe the bug**

Controlling this fan works fine for turning it off, changing the speed, etc. However, when I press the button in lovelace, if the fan is off, it does not turn on, and instead says, "Failed to call service fan/turn_on. 'default'"
**Debug log**

```text

Add your logs here.

`2020-03-27 11:17:18 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1834224656] 'default'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1234, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1257, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 198, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 402, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 599, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 433, in _handle_entity_call
    await result
  File "/config/custom_components/smartir/fan.py", line 224, in async_turn_on
    await self.async_set_speed(speed)
  File "/config/custom_components/smartir/fan.py", line 207, in async_set_speed
    await self.send_command()
  File "/config/custom_components/smartir/fan.py", line 239, in send_command
    command = self._commands[direction][speed]
KeyError: 'default'`

**Comment by mshuflin** [comment]
https://keitetran.github.io/BroadlinkIRTools/ generated a json file with "forward" instead of "default"
