### ISSUE TITLE
Broadlink not working with the latest .110

### ISSUE THREAD

**Issue by ranrinc** [smartHomeHub/SmartIR#357]
**Home Assistant version**
.110

**SmartIR version**
1.10

**SmartIR configuration**

```yaml
smartir:
climate:
  - platform: smartir
    name: Master Bed Room AC
    unique_id: mbr_ac
    device_code: 1100
    controller_data: !secret broad_rm_ip
    temperature_sensor: sensor.temperature
    humidity_sensor: sensor.humidity
    power_sensor: binary_sensor.ac_power
```

**Describe the bug**

The climate shown correctly but the broadlink RM did not working

**Debug log**

```text

Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 338, in send_command
    self._commands[operation_mode][fan_mode][target_temperature])
  File "/config/custom_components/smartir/controller.py", line 85, in send
    'broadlink', 'send', service_data)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1212, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service broadlink/send

```

**Additional context**

**Comment by ranrinc** [comment]
Nevermind.. its working now..

**Comment by RedGuilhas** [comment]
> Nevermind.. its working now..

What did you do to make it working? I'm having the same issue.

Thanks
