### ISSUE TITLE
Fan not working 

### ISSUE THREAD

**Issue by yoni3210** [smartHomeHub/SmartIR#360]
Hi,
Since updating to the last Home Assistant version - 0.110.1, i also updated the Smart IR component to latest version.
The Fan stooped working, when i try turn it on i get the following errors:
![image](https://user-images.githubusercontent.com/39197374/82739817-9a984580-9d4b-11ea-937a-ecf05043b959.png)

error from the logfile:
`2020-05-23 09:59:53 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.139812806421136] 'default'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1288, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 453, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 597, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 484, in _handle_entity_call
    await result
  File "/config/custom_components/smartir/fan.py", line 236, in async_turn_on
    await self.async_set_speed(speed)
  File "/config/custom_components/smartir/fan.py", line 212, in async_set_speed
    await self.send_command()
  File "/config/custom_components/smartir/fan.py", line 254, in send_command
    command = self._commands[direction][speed]
KeyError: 'default'`

Media_Player - Working OK
Climate - Working OK

Appreciate the help.

Thank you,

**Comment by vassilis-panos** [comment]
Could you also send me your json file?

**Comment by yoni3210** [comment]
Done

‫בתאריך שבת, 23 במאי 2020 ב-23:23 מאת ‪Vassilis Panos‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by yoni3210** [comment]
The only thing that i can do is to turn off the device, beside turn it off,
everything else like change speed, turn it on, set a timer, is not working.
---------- Forwarded message ---------
מאת: Yoni Motai <yoni321000@gmail.com>
‪Date: שבת, 23 במאי 2020 ב-23:24‬
Subject: Re: [smartHomeHub/SmartIR] Fan not working (#360)
To: smartHomeHub/SmartIR <
reply@reply.github.com>


Done

‫בתאריך שבת, 23 במאי 2020 ב-23:23 מאת ‪Vassilis Panos‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by vassilis-panos** [comment]
Nothing received. Please zip the file and attach it directly to the issue. Not through email reply.

**Comment by yoni3210** [comment]
[Fan.zip](https://github.com/smartHomeHub/SmartIR/files/4672487/Fan.zip)

**Comment by vassilis-panos** [comment]
Is the problem present in both files?

**Comment by yoni3210** [comment]
no only in the 1000.json - which is the fan

‫בתאריך שבת, 23 במאי 2020 ב-23:52 מאת ‪Vassilis Panos‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by vassilis-panos** [comment]
I can't reproduce your problem. Your 1000.json works well for me.

As I can see you made some changes to the default 1000.json (Kaze fan). Your fan is not supporting two directions, right?

**Comment by yoni3210** [comment]
not quite sure what you mean

**Comment by vassilis-panos** [comment]
So, I cleaned up the file for you. It's a good idea to give a different number as file name since there is an official 1000.json code file. Put the file in custom_components/smartir/codes/fan and change the code in yaml to 4000.
[4000.zip](https://github.com/smartHomeHub/SmartIR/files/4673229/4000.zip)

**Comment by yoni3210** [comment]
Thanks! Issue resolved !!
