### ISSUE TITLE
Fan Component not working

### ISSUE THREAD

**Issue by ceaswaran** [smartHomeHub/SmartIR#361]
**Home Assistant version 0.109.6**

**SmartIR version 1.11.0**

**SmartIR configuration**

```- platform: smartir
  name: Bedroom Smart fan
  unique_id: bedroom_smart_fan
  device_code: 950521
  controller_data: broadlink_rm_ip
  power_sensor: switch.bedroom_fan

```

**Describe the bug**

After adding the component i see fan.bedroom_smartir_fan entitiy but it fails to call sevice. Logs of error attached.
Please help

**Debug log**

```Logger: homeassistant.components.websocket_api.http.connection.140450881780816
Source: custom_components/smartir/fan.py:239
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:20:07 PM (1 occurrences)
Last logged: 11:20:07 PM

'default'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1247, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1282, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 453, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 596, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 484, in _handle_entity_call
    await result
  File "/config/custom_components/smartir/fan.py", line 224, in async_turn_on
    await self.async_set_speed(speed)
  File "/config/custom_components/smartir/fan.py", line 207, in async_set_speed
    await self.send_command()
  File "/config/custom_components/smartir/fan.py", line 239, in send_command
    command = self._commands[direction][speed]
KeyError: 'default'
Failed to call service fan/turn_on. 'default'


```

**Additional context**

**Comment by vassilis-panos** [comment]
Please attach the 950521.json

**Comment by ceaswaran** [comment]
> Please attach the 950521.json

Attached: 
```
{
  "manufacturer": "Orient Electric",
  "supportedModels": [
    "BLDC"
  ],
  "supportedController": "Broadlink",
  "commandsEncoding": "Base64",
  "speed": [
    "level1",
    "level2",
    "level3",
    "level4",
    "level5"
  ],
  "commands": {
    "off": "JgBgAAABJ5QSExITEzgSORITEhMSExM4EjgTOBITEhMTOBI4EzgSExMTEhMSExITEzgSExITExMSOBI5EjgSORITEjgTOBI5EgAFFwABJ0oSAAxeAAEmSxIADF0AASdKEgANBQAAAAAAAAAA",
    "forward": {
      "level1": "JgBYAAABKJQSExITEzgSOBMTEhMSExI5EjgSORITEhMTOBI4EzgSExITExMSOBIUEhMSExITExMSOBI5EhMSOBM4EjgTOBI4EwAFFwABJ0oSAAxdAAEnSxIADQU=",
      "level2": "JgBYAAABJ5QSExITEzgSOBMTEhMSExM4EjgTOBITEhMTOBI4EzgSExI5EhMSORITEhMSExMTEhMSExI5EhMSOBM4EjgTOBI4EwAFFwABJ0oSAAxdAAEnSxIADQU=",
      "level3": "JgBYAAABJpQTExITEjkSOBITExMSExI4EzgSOBMTEhMSORI4EjkSExITEjkSOBITExMSExITExMSOBITExMSOBI5EjgTOBI4EwAFFwABJ0oSAAxeAAEnShIADQU=",
      "level4": "JgBYAAABJ5QSExITEzgSOBMTEhMSExM4EjgTOBITEhQSOBI5EjgSExM4EjkSOBITExMSExITEhMTExITEhMSORI4EzgSOBM4EgAFFwABJ0sSAAxdAAEnSxIADQU=",
      "level5": "JgBYAAABJ5QSExITEzgSOBMTEhMSExI5EjgSORITEhMSORI4EzgSExITExMSExI4ExMSExITEhQSOBI5EjgSExM4EjkSOBI5EgAFFwABJ0sSAAxdAAEnShMADQU="
    }
  }
}
```

**Comment by vassilis-panos** [comment]
Please rename 'forward' key with 'default'. 'forward' key must coexist with 'reverse' key.

**Comment by ceaswaran** [comment]
> Please rename 'forward' key with 'default'. 'forward' key must coexist with 'reverse' key.

Thanks ill give a try & post feedback here soon
