### ISSUE TITLE
xiaomi_miio.climate not found

### ISSUE THREAD

**Issue by shammysha** [smartHomeHub/SmartIR#367]
**Home Assistant version**
0.110.3
**SmartIR version**

**SmartIR configuration**

```yaml

remote:
  - platform: xiaomi_miio
    name: ir_bigroom
    host: 192.168.1.92
    token: *************

climate:
  - platform: smartir
    name: Mitsubishi SRK20ZJ-S BigRoom
    device_code: 999998
    controller_data: remote.ir_bigroom
```

**Describe the bug**

With media_player platform SmartIR works fine. But when I try to add air condition, I have an errors...

**Debug log**
```text
2020-05-28 09:12:22 ERROR (MainThread) [homeassistant.config] Platform error: climate
Traceback (most recent call last):
  File "/var/www/homeassistant/lib/python3.8/site-packages/homeassistant/config.py", line 777, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/var/www/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 272, in get_platform
    cache[full_name] = importlib.import_module(
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'homeassistant.components.xiaomi_miio.climate'
2020-05-28 09:12:22 ERROR (MainThread) [homeassistant.config] Platform error: climate
Traceback (most recent call last):
  File "/var/www/homeassistant/lib/python3.8/site-packages/homeassistant/config.py", line 777, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/var/www/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 272, in get_platform
    cache[full_name] = importlib.import_module(
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'homeassistant.components.xiaomi_miio.climate'
```

**Additional context**
I can not find any additional components , which includes xiaomi_miio/climate.py
Which plugin I must to use with SmartIR for xiaomi IR controller?

**Comment by vassilis-panos** [comment]
You need to fix xiaomi_miio remote integration

**Comment by shammysha** [comment]
I'm follow instructions from https://www.home-assistant.io/integrations/remote.xiaomi_miio/

That is standart component of HomeAssistant in current version.
Which fix i must to apply?

**Comment by vassilis-panos** [comment]
No, you do not need an additional module.
Does the remote.send_command service work properly?

**Comment by vassilis-panos** [comment]
Any chance you can also use https://github.com/syssi/xiaomi_airconditioningcompanion?

**Comment by shammysha** [comment]
> Does the remote.send_command service work properly?
Yes, I'm using Your plugin with satellite box (as media player).

```
- platform: smartir
  name: GS B528 bigroom
  device_code: 999999
  controller_data: remote.ir_bigroom
# power_sensor: binary_sensor.tv_power
  source_names:
    TRICOLOR: 'Триколор ТВ'
    CINEMA: 'Кино'
    BIGTV: 'Большое кино'
    TVGID: 'Телегид'
    RADIO: 'Радио'
```
> Any chance you can also use https://github.com/syssi/xiaomi_airconditioningcompanion?
If there no chances to use Your pugin , then I wil use that.

**Comment by vassilis-panos** [comment]
I'm asking you because I can't imagine from where homeassistant.components.xiaomi_miio.climate comes, except xiaomi_airconditioningcompanion.

**Comment by shammysha** [comment]
Please, excuse me :-)
Have copypasted string in confguration... 

climate: !include_dir_merge_list entities/remote/

My eyes just little confused with syntax :-) 
Corrected that, and now - Your plugin goes Rock again :-)
