### ISSUE TITLE
Unable to find service broadlink/send

### ISSUE THREAD

**Issue by anandsuppiah12** [smartHomeHub/SmartIR#378]
Hi. I'm getting an error with SmartIR.
Device : Broadlink RM Mini 3
Home Assistant version : 0.112.0.dev20200605

Installed by copying SmartIR to custom_components. Yaml Config are as follows : - 
smartir:
  check_updates: false
remote:
  - platform: broadlink
    host: 192.168.1.64
    mac: c8-f7-42-f5-f5-fd   # i also tried 'c8:f7:42:f5:f5:fd' format.

climate:
  - platform: smartir
    name: Master Bedroom Air Conditioner
    unique_id: MBr_AC
    device_code: 1020
    controller_data: 192.168.1.64
    temperature_sensor: sensor.temperature
    humidity_sensor: sensor.humidity
    power_sensor: binary_sensor.ac_power

Error : 
Log Details (ERROR)
Logger: custom_components.smartir.climate
Source: core.py:1218
Integration: SmartIR (documentation)
First occurred: 11:12:53 AM (2 occurrences)
Last logged: 11:12:54 AM

Unable to find service broadlink/send
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 338, in send_command
    self._commands[operation_mode][fan_mode][target_temperature])
  File "/config/custom_components/smartir/controller.py", line 93, in send
    'broadlink', 'send', service_data)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1218, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service broadlink/send
Home Assistant has started!

Full HA Logs 

2020-06-08 11:11:59 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-06-08 11:11:59 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for smartir which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-06-08 11:12:53 ERROR (MainThread) [custom_components.smartir.climate] Unable to find service broadlink/send
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 338, in send_command
    self._commands[operation_mode][fan_mode][target_temperature])
  File "/config/custom_components/smartir/controller.py", line 93, in send
    'broadlink', 'send', service_data)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1218, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service broadlink/send
2020-06-08 11:12:54 ERROR (MainThread) [custom_components.smartir.climate] Unable to find service broadlink/send
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 330, in send_command
    await self._controller.send(self._commands['off'])
  File "/config/custom_components/smartir/controller.py", line 93, in send
    'broadlink', 'send', service_data)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1218, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service broadlink/send
2020-06-08 11:14:29 ERROR (MainThread) [custom_components.smartir.climate] Unable to find service broadlink/send
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 338, in send_command
    self._commands[operation_mode][fan_mode][target_temperature])
  File "/config/custom_components/smartir/controller.py", line 93, in send
    'broadlink', 'send', service_data)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1218, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service broadlink/send
2020-06-08 11:14:30 ERROR (MainThread) [custom_components.smartir.climate] Unable to find service broadlink/send
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 330, in send_command
    await self._controller.send(self._commands['off'])
  File "/config/custom_components/smartir/controller.py", line 93, in send
    'broadlink', 'send', service_data)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1218, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service broadlink/send

**Comment by anandsuppiah12** [comment]
sorry. my mistake. was using the wrong ip address. I cant seem to delete. so will close it.
