### ISSUE TITLE
Errors in upcoming version of HA 0.89

### ISSUE THREAD

**Issue by aidbish** [smartHomeHub/SmartIR#38]
Testing the new beta of the latest version of HA 0.89b1
SmartIR has errors

2019-03-01 07:19:52 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.smartir.climate. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/loader.py", line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/smartir/climate.py", line 17, in <module>
    from homeassistant.components.climate import (
ImportError: cannot import name 'STATE_HEAT' from 'homeassistant.components.climate' (/usr/src/app/homeassistant/components/climate/__init__.py)

2019-03-01 07:19:52 ERROR (MainThread) [homeassistant.loader] Unable to find platform smartir. Search path was limited to path of component: custom_components

**Comment by smartHomeHub** [comment]
Please update the files from rc branch

**Comment by aidbish** [comment]
Works perfectly, thanks for quick response.

**Comment by smartHomeHub** [comment]
If you want to get update notifications from rc branch, configure the component as follows:
```yaml
smartir:
  update_branch: 'rc'
```
