### ISSUE TITLE
HA 0.115 beta breaks broadlink: Unable to find service broadlink/send

### ISSUE THREAD

**Issue by SCUZNUTS** [smartHomeHub/SmartIR#475]
**Home Assistant version**
1.115.0b0

**SmartIR version**
'Latest Stable/RC Version tested'

**SmartIR configuration**
smartir:
climate:
  - platform: smartir
    name: Dining Room Heat Pump
    unique_id: dining_room_heat_pump
    device_code: 1120
    controller_data: 192.168.2.109
    temperature_sensor: sensor.dining_room_temperature
    humidity_sensor: sensor.dining_room_humidity

Switch:
- platform: broadlink
  mac: 'b4:43:0d:f9:34:75'

```yaml


```

**Describe the bug**

The new version of HA moves away from using broadlink/send to using remote.device to send commands.

**Debug log**

```text

Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 337, in send_command
    await self._controller.send(
  File "/config/custom_components/smartir/controller.py", line 92, in send
    await self.hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1265, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service broadlink/send
```

**Additional context**

**Comment by vassilis-panos** [comment]
The fix is ready. I guess as HA beta tester you know what to do :)

**Comment by tayanov** [comment]
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 337, in send_command
    await self._controller.send(
  File "/config/custom_components/smartir/controller.py", line 92, in send
    await self.hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1269, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 208, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 287, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 283, in _exec
    v = func(v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: not a valid value for dictionary value @ data['entity_id']

**Comment by smartHomeHub** [comment]
Please upgrade smartir from Hacs or RC brunch

**Comment by tayanov** [comment]
yes. im upgrade to 1.13 rc wersion early

**Comment by tayanov** [comment]
yea
controller_data: 192.168.0.10
change to
controller_data: remote.rm_mini_remote

**Comment by smartHomeHub** [comment]
Did you resolve the problem ?

**Comment by tayanov** [comment]
yes

**Comment by SCUZNUTS** [comment]
Can confirm rc release works fine.
