### ISSUE TITLE
Broadlink climate with HA 0.115

### ISSUE THREAD

**Issue by Edo78** [smartHomeHub/SmartIR#477]
**Home Assistant version**
0.115

**SmartIR version**
1.12.0

**SmartIR configuration**

```yaml
  - platform: smartir
    name: Camera dei genitori
    unique_id: camera_genitori_ac
    device_code: 1106
    controller_data: x.x.x.x
```

**Describe the bug**

HA version 0.115 discontinue `broadlink.send` now `remote.send_command` should be used to send base64 codes.

**Debug log**

```text
Logger: custom_components.smartir.climate
Source: core.py:1265
Integration: SmartIR (documentation)
First occurred: 19:25:58 (2 occurrences)
Last logged: 19:26:01

Unable to find service broadlink/send
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/smartir/climate.py", line 338, in send_command
    self._commands[operation_mode][fan_mode][target_temperature])
  File "/home/homeassistant/.homeassistant/custom_components/smartir/controller.py", line 93, in send
    'broadlink', 'send', service_data)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1265, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service broadlink/send
```

**Comment by Metus88** [comment]
same problem.
My configuration.yaml:
`smartir: 
media_player:
  - platform: smartir
    name: SalottoIntrattenimento
    device_code: 7777
    controller_data: !secret hostbroadlink`
My error log:
`2020-09-17 19:40:58 ERROR (MainThread) [custom_components.smartir.media_player] Unable to find service broadlink/send
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/smartir/media_player.py", line 267, in send_command
    await self._controller.send(command)
  File "/home/homeassistant/.homeassistant/custom_components/smartir/controller.py", line 93, in send
    'broadlink', 'send', service_data)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1265, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service broadlink/send`

**Comment by vassilis-panos** [comment]
Please update to 1.13
