### ISSUE TITLE
Stopped working on the new update 0.115

### ISSUE THREAD

**Issue by homeranil** [smartHomeHub/SmartIR#479]
Stopped working on the new update 0.115.
In the update they changed the integration with broadlink
And it does not work in the new update

```
not a valid value for dictionary value @ data['entity_id']
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 337, in send_command
    await self._controller.send(
  File "/config/custom_components/smartir/controller.py", line 92, in send
    await self.hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1269, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 208, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 287, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 283, in _exec
    v = func(v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: not a valid value for dictionary value @ data['entity_id']
Failed to call service remote/send_command. extra keys not allowed @ data['devica']
```

**Comment by vassilis-panos** [comment]
Did you also update SmartIR?

**Comment by cllatser** [comment]
Same

**Comment by Profil404** [comment]
Same here. I have the lastest version of SmartIR (1.13.1) and I have this in the logs:

`Logger: custom_components.smartir.climate
Source: core.py:1269
Integration: SmartIR (documentation)
First occurred: 20:46:31 (3 occurrences)
Last logged: 20:46:33

not a valid value for dictionary value @ data['entity_id']
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 337, in send_command
    await self._controller.send(
  File "/config/custom_components/smartir/controller.py", line 101, in send
    await self.hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1269, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 208, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 287, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 283, in _exec
    v = func(v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: not a valid value for dictionary value @ data['entity_id']`

**Comment by cllatser** [comment]
![SmartIR](https://user-images.githubusercontent.com/65849393/93514657-c0171380-f927-11ea-93e0-b467dde3e6d6.jpg)

**Comment by homeranil** [comment]
> Did you also update SmartIR?

yep

**Comment by vassilis-panos** [comment]
Was `controller_data` also updated with the new `remote.xxx` entity?
https://github.com/smartHomeHub/SmartIR/blob/master/docs/CLIMATE.md#example-using-broadlink-controller

**Comment by homeranil** [comment]
> Was `controller_data` also updated with the new `remote.xxx` entity?
> https://github.com/smartHomeHub/SmartIR/blob/master/docs/CLIMATE.md#example-using-broadlink-controller

ohhhh i'm stupid

thanks!!

**Comment by userMak** [comment]
> Was `controller_data` also updated with the new `remote.xxx` entity?
> https://github.com/smartHomeHub/SmartIR/blob/master/docs/CLIMATE.md#example-using-broadlink-controller

Vasili kalhspera
I need some help with the configuration of the broadlink. I am on 0.115 and I can not install broadling as integration.
Can you give me please an example to place for my configuration yaml?
until yesterday I had the following
`#smartir:

#switch:
#  - platform: broadlink
#    host: 192.168.1.xxx
#    mac: '34:EA:34:xx:42:xx'
#    type: "rm_mini"`

how I should change it?

**Comment by homeranil** [comment]
> > Was `controller_data` also updated with the new `remote.xxx` entity?
> > https://github.com/smartHomeHub/SmartIR/blob/master/docs/CLIMATE.md#example-using-broadlink-controller
> 
> Vasili kalhspera
> I need some help with the configuration of the broadlink. I am on HA 0.115 and SmartIR (1.13.1)
> I can not install broadling as integration.
> Can you give me please an example to place for my configuration yaml?
> until yesterday I had the following
> 
> `#smartir:
> 
> #switch:
> 
> # - platform: broadlink
> # host: 192.168.1.xxx
> # mac: '34:EA:34:xx:42:xx'
> # type: "rm_mini"`
> how I should change it?

```
smartir:

switch:
  - platform: broadlink
    host: 192.168.1.xxx
    mac: 34:EA:34:xx:42:xx
```

**Comment by urihersh** [comment]
same here, all of my fans stopped working after the upgrade.

**Comment by jinjie** [comment]
I had the same issue, but that's what we get when we do not read release notes.

There is some major breaking change in Broadlink component.

Read this: https://www.home-assistant.io/blog/2020/09/17/release-115/#breaking-changes

What I did:
- Removed the remote platform and switch platforms in my yaml files
- Setup the integration
- Rename the entities in yaml files accordingly to the new entity id, or you can change the entity id to the one that is already in your yaml files.
- `controller_data` should now be referencing to the remote entity id rather than the IP or mac address.
