### ISSUE TITLE
MQTT IR blaster not working (stack trace printed in HomeAssistant)

### ISSUE THREAD

**Issue by mitnits** [smartHomeHub/SmartIR#483]
**Home Assistant version**
0.115.0

**SmartIR version**
1.13.2 (and 1.13.1, too)

**SmartIR configuration**

```yaml

(in the climate.yaml file included from the main)

- platform: smartir
  name: Office
  device_code: 1340
  unique_id: office
  controller_data: cmnd/irblaster1/IRsend


```

**Describe the bug**

Got a new tasmota IR blaster set up (works by itself, using mosquito_pub). It does not work, stack trace is printed in home assistant log.

```

**Debug log**

```text



2020-09-19 15:04:09 ERROR (MainThread) [custom_components.smartir.climate] not a valid value for dictionary value @ data['entity_id']
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/smartir/climate.py", line 338, in send_command
    self._commands[operation_mode][fan_mode][target_temperature])
  File "/home/homeassistant/.homeassistant/custom_components/smartir/controller.py", line 110, in send
    'remote', 'send_command', service_data)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1269, in async_call
    processed_data = handler.schema(service_data)
  File "/srv/homeassistant/lib/python3.7/site-packages/voluptuous/validators.py", line 208, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/srv/homeassistant/lib/python3.7/site-packages/voluptuous/validators.py", line 287, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/srv/homeassistant/lib/python3.7/site-packages/voluptuous/validators.py", line 283, in _exec
    v = func(v)
  File "/srv/homeassistant/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/srv/homeassistant/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/srv/homeassistant/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/srv/homeassistant/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/srv/homeassistant/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: not a valid value for dictionary value @ data['entity_id']
```

**Comment by smartHomeHub** [comment]
Please send me the json file

**Comment by mitnits** [comment]
The json file used is identical to this: (verified using "diff"):

https://raw.githubusercontent.com/smartHomeHub/SmartIR/master/codes/climate/1340.json

**Comment by smartHomeHub** [comment]
supportedController and  commandsEncoding values?

**Comment by mitnits** [comment]
Sorry, I don’t really understand what you mean.

The supported controller in this case is really only “broadlink” - are you
saying I’ll need to convert this to a different format to use with tasmota
it blaster? If so - any clues on how to do that?

Thanks

**Comment by smartHomeHub** [comment]
You need to make your own file. You can't use files that made for different controllers.
Bellow is an example.
https://github.com/tinet/SmartIR/blob/80d6b7f3f274387922a7cd654ed7422d92ec6196/codes/climate/1065.json
