### ISSUE TITLE
SmartIR stopped working after recent Homeassisant update

### ISSUE THREAD

**Issue by Acetyld** [smartHomeHub/SmartIR#488]
**Home Assistant version**
HassOS 4.13

**SmartIR version**
1.13.2

**SmartIR configuration**

```yaml

smartir:

switch:
  - platform: broadlink
    host: 192.168.2.15
    mac: '78:0F:77:60:B3:75'

climate:
  - platform: smartir
    name: AircoDion
    unique_id: aircodion
    device_code: 4020
    controller_data: 192.168.2.15

```

**Describe the bug**

So it randomly stopped working. And getting these errors inside the console of core

**Debug log**

```text
2020-09-21 20:40:07 ERROR (MainThread) [custom_components.smartir.climate] not a valid value for dictionary value @ data['entity_id']
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 330, in send_command
    await self._controller.send(self._commands['off'])
  File "/config/custom_components/smartir/controller.py", line 109, in send
    await self.hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1269, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 208, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 287, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 283, in _exec
    v = func(v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: not a valid value for dictionary value @ data['entity_id']
```

**Additional context**

**Comment by smartHomeHub** [comment]
https://github.com/smartHomeHub/SmartIR/issues/480#issuecomment-695755305

**Comment by nirkons** [comment]
Also stopped working for me in latest update, the UI works but no IR is being sent, and there is nothing in the error log regarding this.

```
climate:
  - platform: smartir
    name: Livingroom AC
    unique_id: livingroom_ac
    device_code: 4
    controller_data: remote.livingroombroadlink_remote
```

**Comment by smartHomeHub** [comment]
It is impossible not to have an error in the logs.

**Comment by nirkons** [comment]
I dont know what to say, it worked before the latest update (0.115.2) and for years before that :)
I changed to the new format once the new broadlink integration and smartir came out.

![image](https://user-images.githubusercontent.com/24681877/93946139-25606f80-fd41-11ea-85a5-4f6730866867.png)
I'm clicking it a bunch of times, multiple temps/fan speeds etc... nothing is coming out of the broadlink device from climate (but its working on my other "manual" switches with the built in integration)
![image](https://user-images.githubusercontent.com/24681877/93946295-8c7e2400-fd41-11ea-9b5e-85cb31f50f43.png)

**Comment by smartHomeHub** [comment]
Did you try if the remote.send_command service works properly?

**Comment by nirkons** [comment]
Hmm you're right that didnt work for me either, so it turns out that this needs to be turned on (dont know how it got turned off but its such a bad user experience from HA with this new integration)

![image](https://user-images.githubusercontent.com/24681877/93947797-593d9400-fd45-11ea-8932-a0bc3daea678.png)

now its working, thanks for the help

**Comment by smartHomeHub** [comment]
Oh, I do not even know what this switch means.
