### ISSUE TITLE
After HA update to 0.89, component can't be loaded

### ISSUE THREAD

**Issue by callifo** [smartHomeHub/SmartIR#53]
**Home Assistant version**
0.89.0
**SmartIR version**
Latest Master/Latest RC
**SmartIR configuration**

```yaml
climate:
  - platform: smartir
    name: Airconditioner
    device_code: 1000
    controller_send_service: switch.broadlink_send_packet_192_168_10_199
    temperature_sensor: sensor.living_room_temperature_f
```

**Describe the bug**
Component will no longer load, errors as shown in log below,
I've tried versions from both the master repository and rc, neither will start.

**Debug log**

```text
2019-03-07 19:09:01 ERROR (SyncWorker_19) [homeassistant.loader] Error loading custom_components.smartir.climate. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/smartir/climate.py", line 20, in <module>
    from . import COMPONENT_ABS_DIR, Helper
ImportError: cannot import name 'COMPONENT_ABS_DIR' from 'custom_components.smartir' (/home/homeassistant/.homeassistant/custom_components/smartir/__init__.py)
2019-03-07 19:09:01 ERROR (SyncWorker_19) [homeassistant.loader] Unable to find platform smartir. Search path was limited to path of component: custom_components
2019-03-07 19:09:03 ERROR (SyncWorker_19) [homeassistant.loader] Error loading custom_components.sharp_aquos. Make sure all dependencies are installed

```

**Additional context**
```

```

**Comment by smartHomeHub** [comment]
Is `smartir:` in your configuration?
```yaml
smartir:

climate:
  - platform: smartir
    name: Airconditioner
    device_code: 1000
    controller_send_service: switch.broadlink_send_packet_192_168_10_199
    temperature_sensor: sensor.living_room_temperature_f
```

**Comment by callifo** [comment]
Yep, just the line,
```
smartir:
```

**Comment by callifo** [comment]
custom_component\smartir looks like this:
-rw-r--r-- 1 homeassistant homeassistant  14K Mar  7 19:08 climate.py
drwxr-xr-x 3 homeassistant homeassistant 4.0K Feb 23 12:49 codes
-rw-r--r-- 1 homeassistant homeassistant 3.2K Mar  7 19:08 controller.py
-rw-r--r-- 1 homeassistant homeassistant 9.0K Mar  7 19:08 fan.py
-rw-r--r-- 1 homeassistant homeassistant 5.4K Mar  7 19:08 __init__.py
-rw-r--r-- 1 homeassistant homeassistant 9.5K Mar  7 19:08 media_player.py
drwxr-xr-x 2 homeassistant homeassistant 4.0K Mar  7 19:12 __pycache__

**Comment by cfort69** [comment]
same issue here and same files in custom_component\smartir

**Comment by smartHomeHub** [comment]
Did you get this error while you press restart in HA config panel? Did you try to reboot your system?

**Comment by patrik996** [comment]
Im also getting the same error:
Error loading custom_components.smartir.climate. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/loader.py", line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/smartir/climate.py", line 20, in <module>
    from . import COMPONENT_ABS_DIR, Helper
ImportError: cannot import name 'COMPONENT_ABS_DIR' from 'custom_components.smartir' (/config/custom_components/smartir/__init__.py)

**Comment by smartHomeHub** [comment]
Could you also remove the __pycache__ folder and try to restart again?

**Comment by patrik996** [comment]
> Could you also remove the **pycache** folder and try to restart again?

I tried that right now. Same error.

**Comment by patrik996** [comment]
This might have something to do with it.
https://developers.home-assistant.io/blog/2019/02/19/the-great-migration.html

**Comment by patrik996** [comment]
Sorry, my bad. After replacing the code from RC-branch it resolved all errors. https://github.com/smartHomeHub/SmartIR/tree/rc

**Comment by smartHomeHub** [comment]
Strange. rc and master code is identical.

**Comment by patrik996** [comment]
> Strange. rc and master code is identical.

weird. maybe it was something cached after all.

**Comment by callifo** [comment]
Yeah looks like something there did it, deleting pycache doesn't seem to be enough. I touched the files to make them appear newer, and deleted pycache and its now loaded fine. I had blown away pycache that many times already to no affect.

This is the second one like that. I had my own custom component that needed const.py added from the inbuilt component. I had added the wrong one initially and it complained some variables were missing. I replaced it with the correct one, deleted pycache and restarted. Nothing... kept complaining it was missing.

Posted a thread and someone suggested doing something that just resulted in updating the files last modified date, and boom, all good.

**Comment by CountParadox** [comment]
Hey everyone, I am getting the same error......

`Fri Mar 08 2019 15:00:32 GMT+1100 (Australian Eastern Daylight Time)
Error loading custom_components.smartir.climate. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/smartir/climate.py", line 9, in <module>
    from homeassistant.components.climate.const import (
ImportError: cannot import name 'STATE_HEAT' from 'homeassistant.components.climate.const' (/usr/local/lib/python3.7/site-packages/homeassistant/components/climate/const.py)
Service homeassistant/restart called.
`


Trying things mentioned in this issue have not resolved it for me, I do have smartir: in my configuration.yaml....

**Comment by vietdht** [comment]
@CountParadox You should remove all old files in custom_components/smartir, then copy new file from release branch again. I faced same error when using old files with HA 0.89
