### ISSUE TITLE
How  climate.set_fan_mode can be executed?

### ISSUE THREAD

**Issue by wojciechczyz** [smartHomeHub/SmartIR#530]
**Home Assistant version**
0.118.3

**SmartIR version**
1.13.2

**SmartIR configuration**

```yaml

Add configuration here

```

**Describe the bug**

Cannot execute 
climate.set_fan_mode 

I have tried:
fan_mode: 'On Low'
fan_mode: 'Low'
fan_mode: 'Speed Low'
fan_mode: 'Speed_Low'

Yet all get error such as below. What is the correct way to control fan_mode?

**Debug log**

```text

Add your logs here.

2020-11-24 00:13:47 ERROR (MainThread) [custom_components.smartir.climate] 'Speed Low'
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 338, in send_command
    self._commands[operation_mode][fan_mode][target_temperature])
KeyError: 'Speed Low'
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 338, in send_command
    self._commands[operation_mode][fan_mode][target_temperature])
KeyError: 'Speed Low'
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 338, in send_command
    self._commands[operation_mode][fan_mode][target_temperature])
KeyError: 'Speed Low'
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 338, in send_command
    self._commands[operation_mode][fan_mode][target_temperature])
KeyError: 'Speed Low'


**Additional context**

Add any other context about the problem here.

**Comment by vassilis-panos** [comment]
Hello,
Try lowercase.
```

entity_id: climate.office_ac
fan_mode: low
```
