### ISSUE TITLE
Delay should be converted to float

### ISSUE THREAD

**Issue by eyalcha** [smartHomeHub/SmartIR#571]
`self._delay = float(config.get(CONF_DELAY))
`

As 

`await asyncio.sleep(self._delay)
`
requires number

**Comment by patrik996** [comment]
I think I'm having an issue with this:

'<=' not supported between instances of 'str' and 'int'
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 341, in send_command
    await asyncio.sleep(self._delay)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 643, in sleep
    if delay <= 0:
TypeError: '<=' not supported between instances of 'str' and 'int'

**Comment by agneevX** [comment]
Yep, same error here with the following logs

```py
2021-01-27 22:48:39 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/config/core.py", line 29, in post
    errors = await async_check_ha_config_file(request.app["hass"])
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/config.py", line 866, in async_check_ha_config_file
    res = await check_config.async_check_ha_config_file(hass)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/check_config.py", line 164, in async_check_ha_config_file
    platform = p_integration.get_platform(domain)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 402, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/smartir/climate.py", line 48, in <module>
    vol.Optional(CONF_DELAY, default=DEFAULT_DELAY): cv.positive_float,
AttributeError: module 'homeassistant.helpers.config_validation' has no attribute 'positive_float'
```

**Comment by vassilis-panos** [comment]
@agneevX This is something else. Why is possitive_float not available in your instance ? Which version are you running?

**Comment by vassilis-panos** [comment]
It seems that positive_float merged @11 Oct 2020. So I bet you are running an old instance.
You need to update.

**Comment by agneevX** [comment]
I'm running 0.115.6.

**Comment by agneevX** [comment]
@vassilis-panos SmartIR is already up to date. Why am I still getting this error then?

**Comment by vassilis-panos** [comment]
You need to update HA also
