### ISSUE TITLE
error after last update

### ISSUE THREAD

**Issue by acidquest** [smartHomeHub/SmartIR#64]
I update HA to 0.89.1 from 0.88. SmartIR update too. After that i have error and component not working.
I don't change configuration, only update

2019-03-11 14:34:01 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.smartir.climate. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/loader.py", line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/acidquest/.homeassistant/custom_components/smartir/climate.py", line 17, in <module>
    from homeassistant.components.climate import (
ImportError: cannot import name 'STATE_HEAT'
2019-03-11 14:34:01 ERROR (MainThread) [homeassistant.loader] Unable to find platform smartir. Search path was limited to path of component: custom_components
2019-03-11 14:43:03 ERROR (SyncWorker_3) [homeassistant.loader] Error loading custom_components.smartir.climate. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/loader.py", line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/acidquest/.homeassistant/custom_components/smartir/climate.py", line 20, in <module>
    from . import COMPONENT_ABS_DIR, Helper
ImportError: cannot import name 'COMPONENT_ABS_DIR'
2019-03-11 14:43:03 ERROR (SyncWorker_3) [homeassistant.loader] Unable to find platform smartir. Search path was limited to path of component: custom_components

**Comment by acidquest** [comment]
Please close issue.

I updated the component again, this time manually. after that, everything worked. The first time I updated using the update service.
