### ISSUE TITLE
[custom_components.smartir.climate] not a valid value for dictionary value @ data['entity_id']

### ISSUE THREAD

**Issue by dchigiani** [smartHomeHub/SmartIR#648]
**Home Assistant version**
core-2021.6.5

**SmartIR version**
1.16.1

**SmartIR configuration**

```yaml
smartir:

climate:
  - platform: smartir
    name: Bedroom AC
    unique_id: bedroom_ac_1
    device_code: 1700
    controller_data: 192.168.0.100
    temperature_sensor: sensor.0x158d000254079a_temperature
    humidity_sensor: sensor.0x158d000254079a_humidity
```

**Describe the bug**

I see error in log my server

**Debug log**

```text

2021-06-19 00:00:21 ERROR (MainThread) [custom_components.smartir.climate] not a valid value for dictionary value @ data['entity_id']
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 377, in send_command
    await self._controller.send(
  File "/config/custom_components/smartir/controller.py", line 111, in send
    await self.hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1445, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 215, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 341, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 339, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: not a valid value for dictionary value @ data['entity_id']

```

**Additional context**

I am using the LOOK.in Remote controller. The entity is being created correctly, but any action with the entity causes an error.

**Comment by vassilis-panos** [comment]
Wow! How many years do you have to update the Home Assistant?

**Comment by dchigiani** [comment]
Did not understand you

**Comment by vaproloff** [comment]
I have the same problem using MQTT

`
- platform: smartir
  name: MQTT AC
  unique_id: mqtt_ac
  device_code: 6666
  controller_data: homeassistant/mqtt-ac/command
`

Thermostat doesn't publish MQTT command.
I have an error:
not a valid value for dictionary value @ data['entity_id']

At the same time integration with Xiaomi controller works correctly.

**Comment by Veda82** [comment]
I have the same problem.

**Comment by vaproloff** [comment]
> I have the same problem.

I've solved it. You should change a file with codes:
```
...
  "supportedController":"MQTT",
  "commandsEncoding":"Raw",
...
```
