### ISSUE TITLE
controller_send_service: mqtt.publish not work

### ISSUE THREAD

**Issue by hoangminh5210119** [smartHomeHub/SmartIR#75]
hi everyone, i have a problem with controller_send_service: mqtt.publish, i try with controller_send_service: switch.broadlink_send_packet_192_168_1_29 work well, but mqtt is not.
this is my log 
`2019-03-16 17:26:52 ERROR (MainThread) [custom_components.smartir.climate] extra keys not allowed @ data['packet']
Traceback (most recent call last):
  File "/Users/minhsuong/.homeassistant/custom_components/smartir/climate.py", line 334, in send_command
    await self._controller.send(command)
  File "/Users/minhsuong/.homeassistant/custom_components/smartir/controller.py", line 81, in send
    service_data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/homeassistant/core.py", line 1113, in async_call
    processed_data = handler.schema(service_data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 267, in __call__
    return self._compiled([], data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 589, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 427, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['packet']`
thanks

**Comment by smartHomeHub** [comment]
Did you define the controller as 'MQTT' in your Json file?

**Comment by smartHomeHub** [comment]
```
{
  "manufacturer": "Toyotomi",
  "supportedModels": [
    "AKIRA GAN/GAG-A128 VL"
  ],
  "supportedController": "MQTT",
  "commandsEncoding": "Raw",
....
```

**Comment by hoangminh5210119** [comment]
awesome. thank you very much
