### ISSUE TITLE
Suddenly SmartIR Climate stopped working

### ISSUE THREAD

**Issue by cubilon** [smartHomeHub/SmartIR#78]
**Home Assistant version** : 0.89.2 and 0.90
**SmartIR version** 1.3.9

**Describe the bug**

Suddenly SmartIR Climate stopped working. When I try sending heat command, fails to call service climate/set_operation_mode. Tried updating to 0.90, same problem.
On/off works.

**Debug log**

```
Mar 21 09:19:33 raspberrypi hass[19228]: 2019-03-21 09:19:33 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1724282256] ''
Mar 21 09:19:33 raspberrypi hass[19228]: Traceback (most recent call last):
Mar 21 09:19:33 raspberrypi hass[19228]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/websocket_api/commands.py", line 122, in handle_call_service
Mar 21 09:19:33 raspberrypi hass[19228]:     connection.context(msg))
Mar 21 09:19:33 raspberrypi hass[19228]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/core.py", line 1138, in async_call
Mar 21 09:19:33 raspberrypi hass[19228]:     self._execute_service(handler, service_call))
Mar 21 09:19:33 raspberrypi hass[19228]:   File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
Mar 21 09:19:33 raspberrypi hass[19228]:     yield self  # This tells Task to wait for completion.
Mar 21 09:19:33 raspberrypi hass[19228]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
Mar 21 09:19:33 raspberrypi hass[19228]:     future.result()
Mar 21 09:19:33 raspberrypi hass[19228]:   File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
Mar 21 09:19:33 raspberrypi hass[19228]:     raise self._exception
Mar 21 09:19:33 raspberrypi hass[19228]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
Mar 21 09:19:33 raspberrypi hass[19228]:     result = coro.send(None)
Mar 21 09:19:33 raspberrypi hass[19228]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/core.py", line 1160, in _execute_service
Mar 21 09:19:33 raspberrypi hass[19228]:     await handler.func(service_call)
Mar 21 09:19:33 raspberrypi hass[19228]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_component.py", line 188, in handle_service
Mar 21 09:19:33 raspberrypi hass[19228]:     self._platforms.values(), func, call, service_name
Mar 21 09:19:33 raspberrypi hass[19228]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/service.py", line 314, in entity_service_call
Mar 21 09:19:33 raspberrypi hass[19228]:     future.result()  # pop exception if have
Mar 21 09:19:33 raspberrypi hass[19228]:   File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
Mar 21 09:19:33 raspberrypi hass[19228]:     raise self._exception
Mar 21 09:19:33 raspberrypi hass[19228]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
Mar 21 09:19:33 raspberrypi hass[19228]:     result = coro.send(None)
Mar 21 09:19:33 raspberrypi hass[19228]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/service.py", line 328, in _handle_service_platform_call
Mar 21 09:19:33 raspberrypi hass[19228]:     await getattr(entity, func)(**data)
Mar 21 09:19:33 raspberrypi hass[19228]:   File "/home/homeassistant/.homeassistant/custom_components/smartir/climate.py", line 299, in async_set_operation_mode
Mar 21 09:19:33 raspberrypi hass[19228]:     await self.send_command()
Mar 21 09:19:33 raspberrypi hass[19228]:   File "/home/homeassistant/.homeassistant/custom_components/smartir/climate.py", line 331, in send_command
Mar 21 09:19:33 raspberrypi hass[19228]:     command = self._commands[operation_mode][fan_mode][target_temperature]
Mar 21 09:19:33 raspberrypi hass[19228]: KeyError: ''
```

**Comment by cubilon** [comment]
Now it's working again.
To solve, I checked entity details and I saw that fan mode had no setting. I triedy with "high", than I tried again to set heat mode, and it worked.
I don't know why fan had no value, by the way if it's not set, climate/set_operation_mode doens't work.
