### ISSUE TITLE
SmartIR climate not working on 0.90.1

### ISSUE THREAD

**Issue by gabrielboliveira** [smartHomeHub/SmartIR#80]
**Home Assistant version**
0.90.1

**SmartIR version**
1.3.9 (master branch)

**SmartIR configuration**

```yaml
smartir:

switch:
  - platform: broadlink
    host: <local-ip-removed>
    mac: 'mac-address-removed'
    type: rm_mini
    
climate:
  - platform: smartir
    name: Room AC
    device_code: 1060
    controller_send_service: switch.broadlink_send_packet_my_ip
```

**Describe the bug**

This integration suddenly stopped working. I had a very old version of it, so I thought it was outdated, so I manually updated all `smartir` files. Then, it did not work yet. 

Using the "Config Check" button I see a `Platform not found: climate.smartir` error.

Also there's a few errors popping up on the log, see below.

**Debug log**

```text
Unable to find platform smartir. Search path was limited to path of component: custom_components
```

```text
Error loading custom_components.smartir.climate. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/smartir/climate.py", line 20, in <module>
    from . import COMPONENT_ABS_DIR, Helper
ImportError: cannot import name 'COMPONENT_ABS_DIR' from 'custom_components.smartir' (/config/custom_components/smartir/__init__.py)
```

```text
Error loading custom_components.smartir.climate. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/smartir/climate.py", line 17, in <module>
    from homeassistant.components.climate import (
ImportError: cannot import name 'STATE_HEAT' from 'homeassistant.components.climate' (/usr/local/lib/python3.7/site-packages/homeassistant/components/climate/__init__.py)
```

**Additional context**

Here's a picture of my config folders:
<img width="184" alt="image" src="https://user-images.githubusercontent.com/11093090/54879986-94909700-4e1e-11e9-8c44-1b0eece33a02.png">

**Comment by gabrielboliveira** [comment]
Well, suddenly started working again. Looks like a host reboot solved my problem.
