### ISSUE TITLE
ServiceNotFound: Unable to find service remote.send_command

### ISSUE THREAD

**Issue by spikked27** [smartHomeHub/SmartIR#812]
**Home Assistant version**
Home Assistant 2022.3.8
**SmartIR version**
1.17.5
**SmartIR configuration**

```yaml

esphome:
  name: esp-ac-livingroom

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  services:
    - service: send_raw_command
      variables:
        command: int[]
      then:
        - remote_transmitter.transmit_raw:
            code: !lambda 'return command;'

remote_transmitter:
  pin: D6
  carrier_duty_percent: 50%
  
ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:
  

```
**Home Assistant Config**
```yaml
smartir:
  check_updates: false
  
climate:
  - platform: smartir
    name: LivingRoom AC1063
    unique_id: livingroom_ac1063
    device_code: 1063
    controller_data: esp_ac_livingroom_send_raw_command
```
**Describe the bug**

I get no response from ESPHome Log indicating that service call for send_raw_command was received and no reaction from the device.   Home Assistant Logs state "ServiceNotFound: Unable to find service remote.send_command"

**Debug log**

```text

Logger: custom_components.smartir.climate
Source: core.py:1583
Integration: SmartIR ([documentation](https://github.com/smartHomeHub/SmartIR))
First occurred: 6:01:01 PM (6 occurrences)
Last logged: 6:01:55 PM

Unable to find service remote.send_command
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 366, in send_command
    await self._controller.send(self._commands['off'])
  File "/config/custom_components/smartir/controller.py", line 111, in send
    await self.hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1583, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service remote.send_command

```

**Additional context**

**Comment by ilricky** [comment]
Hi, what was the problem?

**Comment by btzs** [comment]
I am assuming the user forgot `remote:` in their HA /config/configuration.yaml to activate the integration.

**Comment by vpzomtrrfrt** [comment]
How can you forget something that's not referenced in the documentation?
