### ISSUE TITLE
Hassio 0.90.2 Platform not found: climate.smartir

### ISSUE THREAD

**Issue by pilievwm** [smartHomeHub/SmartIR#84]
**Home Assistant version**
0.90.2

**SmartIR version**
1.3.9

Add configuration here

```

When i updated to the 0.90.2 version I get this errors:
Platform not found: climate.smartir

In my dev-info it reads:
Unable to find platform smartir. Search path was limited to path of component: custom_components

**Debug log**

```Error loading custom_components.smartir.climate. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/smartir/climate.py", line 20, in <module>
    from . import COMPONENT_ABS_DIR, Helper
ImportError: cannot import name 'COMPONENT_ABS_DIR' from 'custom_components.smartir' (/config/custom_components/smartir/__init__.py)

```

**Comment by brent0np** [comment]
Can you post your config?

**Comment by craigdent** [comment]
I get the same error and I’ve just installed the smartir component and on hassio 0.90.2

Config

switch:
  - platform: broadlink
    host: xxx.xxx.xxx.xxx
    mac: 'xx:xx:xx:xx:xx:xx'

climate:
  - platform: smartir
    name: Living AC
    unique_id: living_ac
    device_code: 1680
    controller_send_services: switch.broadlink_send_packet_xxx_xxx_xxx_xxx
    temperature_sensor: sensor.netatmo_indoor_temperature
    humidity_sensor: sensor.netatmo_indoor_humidity

**Comment by craigdent** [comment]
Mine corrected itself after few reboots

**Comment by brent0np** [comment]
I can also see you are using;
controller_send_service**s**: switch.broadlink_send_packet_xxx_xxx_xxx_xxx

I believe that should be;
controller_send_service: switch.broadlink_send_packet_xxx_xxx_xxx_xxx

**Comment by craigdent** [comment]
Good eye! Thanks for that. Luckily I deleted that config after I posted and then redid it too

But thank you for picking that up. Would of driven me crazy not noticing that
