### ISSUE TITLE
Error setting up ESPHome-based remote with Pronto codes

### ISSUE THREAD

**Issue by Didgeridrew** [smartHomeHub/SmartIR#872]
**Home Assistant version**

HA core-2022.6.6
Home Assistant OS 8.2

**SmartIR version**
1.17.6 (added using HACS)

**SmartIR configuration**

```yaml

smartir:
  check_updates: false

media_player:
  - platform: smartir
    name: RCA Stereo Receiver
    device_class: receiver
    device_code: 2447
    controller_data: ble_router_1_send_pronto_command
    source_names:
      TV: null
      VCR: null
      Cable: Main

```

**Describe the bug**

Media player is not created, error message below.  The codes have been verified to be work on the device using the service call which is set in `controller_data:`.  If I set `"commandsEncoding": "Raw"` the media player entity is created but none of the functions work.

**Debug log**

```text

Logger: homeassistant.components.media_player
Source: custom_components/smartir/controller.py:178
Integration: Media player (documentation, issues)
First occurred: 09:57:20 (1 occurrences)
Last logged: 09:57:20

Error while setting up smartir platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/smartir/media_player.py", line 82, in async_setup_platform
    async_add_entities([SmartIRMediaPlayer(
  File "/config/custom_components/smartir/media_player.py", line 146, in __init__
    self._controller = get_controller(
  File "/config/custom_components/smartir/controller.py", line 41, in get_controller
    return controllers[controller](hass, controller, encoding, controller_data, delay)
  File "/config/custom_components/smartir/controller.py", line 49, in __init__
    self.check_encoding(encoding)
  File "/config/custom_components/smartir/controller.py", line 178, in check_encoding
    raise Exception("The encoding is not supported "
Exception: The encoding is not supported by the ESPHome controller.

```

**Additional context**

```json
{
    "manufacturer": "RCA",
    "supportedModels": ["RT2360"],
    "supportedController": "ESPHome",
    "commandsEncoding": "Pronto",
    "commands": {
        "off": "0000 0048 0000 001a 00e3 00e1 001d 0036 001d 0072 001d 0036 001d 0072 001d 0036 001d 0036 001d 0072 001d 0072 001d 0072 001d 0036 001d 0072 001d 0072 001d 0072 001d 0036 001d 0072 001d 0036 001d 0036 001d 0036 001d 0036 001d 0072 001d 0036 001d 0036 001d 01e9",
        "on": "0000 0048 0000 001a 00e3 00e1 001d 0036 001d 0072 001d 0036 001d 0072 001d 0036 001d 0036 001d 0072 001d 0072 001d 0072 001d 0036 001d 0072 001d 0072 001d 0072 001d 0036 001d 0072 001d 0036 001d 0036 001d 0036 001d 0036 001d 0072 001d 0036 001d 0036 001d 01e9",
        "mute": "0000 0048 0000 001a 00e3 00e1 001d 0072 001d 0072 001d 0072 001d 0072 001d 0036 001d 0036 001d 0072 001d 0072 001d 0072 001d 0072 001d 0072 001d 0072 001d 0036 001d 0036 001d 0036 001d 0036 001d 0072 001d 0072 001d 0036 001d 0036 001d 0036 001d 0036 001d 0036 001d 0036 001d 01da",
        "volumeUp": "0000 0048 0000 001a 00e3 00e1 001d 0072 001d 0072 001d 0072 001d 0072 001d 0036 001d 0036 001d 0072 001d 0036 001d 0072 001d 0072 001d 0072 001d 0072 001d 0036 001d 0036 001d 0036 001d 0036 001d 0072 001d 0072 001d 0036 001d 0072 001d 0036 001d 0036 001d 0036 001d 0036 001d 01d8",
        "volumeDown": "0000 0048 0000 001a 00e3 00e1 001d 0072 001d 0072 001d 0072 001d 0072 001d 0036 001d 0036 001d 0072 001d 0036 001d 0072 001d 0072 001d 0072 001d 0036 001d 0036 001d 0036 001d 0036 001d 0036 001d 0072 001d 0072 001d 0036 001d 0072 001d 0036 001d 0036 001d 0036 001d 0072 001d 01dd",
        "sources": {
            "Cable": "0000 0048 0000 001a 00e5 00e5 001d 0039 001d 0072 001d 0072 001d 0072 001d 0039 001d 0039 001d 0072 001d 0072 001d 0072 001d 0039 001d 0072 001d 0039 001d 0072 001d 0039 001d 0039 001d 0039 001d 0072 001d 0072 001d 0039 001d 0039 001d 0039 001d 0072 001d 0039 001d 0072 001d 0221",
            "VCR": "0000 0048 0000 001a 00e5 00e5 001d 0072 001d 0072 001d 0072 001d 0039 001d 0039 001d 0039 001d 0072 001d 0072 001d 0072 001d 0039 001d 0072 001d 0039 001d 0039 001d 0039 001d 0039 001d 0072 001d 0072 001d 0072 001d 0039 001d 0039 001d 0039 001d 0072 001d 0039 001d 0072 001d 0221",
            "TV": "0000 0048 0000 001a 00e5 00e5 001d 0072 001d 0072 001d 0072 001d 0072 001d 0039 001d 0039 001d 0072 001d 0072 001d 0072 001d 0039 001d 0072 001d 0039 001d 0039 001d 0039 001d 0039 001d 0039 001d 0072 001d 0072 001d 0039 001d 0039 001d 0039 001d 0072 001d 0039 001d 0072 001d 0221",
            "DVD": "0000 0048 0000 001a 00e3 00e1 001d 0036 001d 0072 001d 0036 001d 0072 001d 0036 001d 0036 001d 0072 001d 0072 001d 0072 001d 0036 001d 0072 001d 0036 001d 0072 001d 0036 001d 0072 001d 0036 001d 0072 001d 0072 001d 0036 001d 0036 001d 0036 001d 0072 001d 0036 001d 0072 001d 01df",
            "AUX": "0000 0048 0000 001a 00e5 00e5 001d 0072 001d 0072 001d 0039 001d 0072 001d 0039 001d 0039 001d 0072 001d 0072 001d 0072 001d 0039 001d 0072 001d 0039 001d 0039 001d 0039 001d 0072 001d 0039 001d 0072 001d 0072 001d 0039 001d 0039 001d 0039 001d 0072 001d 0039 001d 0072 001d 0222",
            "AM/FM": "0000 0048 0000 001a 00e5 00e5 001d 0072 001d 0072 001d 0039 001d 0039 001d 0039 001d 0039 001d 0072 001d 0072 001d 0072 001d 0039 001d 0072 001d 0039 001d 0039 001d 0039 001d 0072 001d 0072 001d 0072 001d 0072 001d 0039 001d 0039 001d 0039 001d 0072 001d 0039 001d 0072 001d 0222"
        }
    }
}
```

**Comment by vassilis-panos** [comment]
Try to change commandsEncoding to Raw

**Comment by Didgeridrew** [comment]
> Try to change commandsEncoding to Raw

If I set `"commandsEncoding": "Raw"` the media player entity is created but none of the functions work.  I'm using the Pronto codes because I could not get any of the raw codes that I captured to work using a `send_raw_command` service call.

**Comment by vincegre** [comment]
+1 at @Didgeridrew  issue ! I have some remote also captured that works only in Pronto format with ESPHome so please support it ;) would be fantastic :)

**Comment by vashilov** [comment]
> > Try to change commandsEncoding to Raw
> 
> If I set `"commandsEncoding": "Raw"` the media player entity is created but none of the functions work. I'm using the Pronto codes because I could not get any of the raw codes that I captured to work using a `send_raw_command` service call.

Are you have error in HA log, when press any button on card device?
I use Hex code and Raw mode.
I have error
json.decoder.JSONDecodeError: Extra data: line

**Comment by antonio1475** [comment]
I got SmartIR to work with Pronto codes!! (Excited because my coding skills are non-existant). Took a bit.

Based on your code from https://github.com/smartHomeHub/SmartIR/issues/958

**controller.py**

```
#line 28, add ENC_PRONTO
ESPHOME_COMMANDS_ENCODING = [ENC_RAW, ENC_PRONTO]
```
```
#line 172 and below, replace with:
class ESPHomeController(AbstractController):
    """Controls a ESPHome device."""

    def check_encoding(self, encoding):
        """Check if the encoding is supported by the controller."""
        if encoding not in ESPHOME_COMMANDS_ENCODING:
            raise Exception("The encoding is not supported "
                            "by the ESPHome controller.")
    
    async def send(self, command):
        """Send a command."""
        if self._encoding == ENC_RAW:
            try:
                service_data = {'command':  json.loads(command)}
            except:
                raise Exception("Error while send raw")

        if self._encoding == ENC_PRONTO:
            try:
                service_data = {'command':  command}
            except:
                raise Exception("Error while send pronto")

        await self.hass.services.async_call(
            'esphome', self._controller_data, service_data)
```
Note that this doesn't include your HEX option but it can be added as well!

**configuration.yaml** needs to have the ESPHome send_pronto_command service instead of send_raw_command:
```
smartir:

climate:
  - platform: smartir
    name: Office AC
    unique_id: office_ac
    device_code: 1070999
    controller_data: ir_rf_send_pronto_command  # THIS!
    temperature_sensor: sensor.temperatura_despacho_temperature
    humidity_sensor: sensor.temperatura_despacho_humidity
```

And this means that the **ESPHome code** needs to include this pronto service as well:
```
api:
  encryption:
    key: "abc123"
  services:
    - service: send_raw_command
      variables:
        command: int[]
      then:
        - remote_transmitter.transmit_raw:
            code: !lambda 'return command;'
    - service: send_pronto_command
      variables:
        command: string
      then:
      - remote_transmitter.transmit_pronto:
          data: !lambda 'return command;'
```


And of course the SmartIR codes json needs to be in Pronto (commandsEncoding, supportedController, the codes themselves which can be converted from other files using https://pasthev.github.io/sensus/):
```
{
  "manufacturer":"LG",
  "supportedModels":[
    "PC09SQ NSJ" , "S12BF"
  ],
  "commandsEncoding":"Pronto",
  "supportedController":"ESPHome",
  "minTemperature":18,
  "maxTemperature":30,
  "precision":1,
  "operationModes":[
    "cool",
    "heat",
    "dry",
    "fan_only",
    "auto"
  ],
  "fanModes":[
    "auto",
    "low",
    "mid",
    "high"
  ],
  "commands":{
    "off":"0000 006d 001e 0000 007a 0175 0016 0039 0016 0013 0015 0013 0015 0013 0015 003a 0013 0015 0015 0013 0015 0013 0015 003a 0015 003a 0015 0013 0015 0013 0015 0013 0014 0014 0014 0013 0015 0013 0015 0013 0015 0013 0013 0015 0015 0013 0015 0013 0015 003a 0015 0013 0015 003a 0015 0013 0015 0013 0015 0013 0015 003a 0015 0f14",
    "cool":{
      "auto":{
        "18":"0000 006d 001e 0000 007c 0174 0015 003a 0016 0011 0015 0014 0015 0013 0015 003a 0015 0011 0016 0013 0015 0013 0015 0013 0015 0011 0016 0011 0015 0013 0016 0011 0016 0013 0015 0013 0015 0013 0015 0013 0015 0013 0015 0039 0016 0039 0015 0013 0015 003a 0015 0013 0015 0039 0016 0039 0015 0013 0015 0013 0015 0013 0015 0f14",
        "19":"0000 006d 001e 0000 007c 0173 0016 0039 0016 0013 0015 0014 0014 0013 0016 003a 0014 0013 0015 0014 0014 0013 0015 0013 0015 0013 0015 0013 0014 0013 0016 0013 0015 0014 0014 0013 0015 0014 0014 0013 0015 003a 0014 0014 0014 0014 0014 0014 0014 003b 0014 0014 0014 003a 0015 003a 0015 0014 0014 0014 0014 003a 0015 0f14",
        "20":"0000 006d 001e 0000 0078 0177 0013 003c 0014 0015 0013 0015 0013 0015 0013 003c 0013 0015 0011 0016 0011 0016 0011 0016 0011 0016 0011 0016 0011 0016 0011 0015 0013 0015 0013 0015 0013 0015 0013 0015 0013 003c 0011 0016 0011 003c 0013 0015 0013 003b 0014 0015 0013 003c 0013 003c 0013 0015 0013 003d 0011 0015 0013 0f14",
        "21":"0000 006d 001e 0000 007a 0177 0013 003c 0013 0016 0011 0015 0013 0016 0011 003c 0013 0015 0013 0015 0013 0015 0013 0015 0013 0015 0013 0015 0013 0015 0011 0016 0011 0016 0011 0016 0011 0016 0011 0016 0011 003c 0013 003c 0011 0016 0011 0016 0011 003c 0013 0015 0013 003d 0011 003d 0011 0015 0013 003d 0011 003c 0013 0f14",
        "22":"0000 006d 001e 0000 007a 0177 0013 003c 0013 0015 0013 0015 0013 0015 0013 003c 0011 0016 0011 0016 0011 0015 0014 0015 0011 0016 0011 0016 0011 0015 0013 0016 0011 0016 0011 0015 0013 0015 0013 0015 0013 003c 0013 003c 0011 003d 0013 0015 0013 003c 0013 0015 0013 003c 0013 003c 0013 003c 0011 0016 0011 0016 0011 0f14",
        "23":"0000 006d 001e 0000 007b 0176 0013 003c 0014 0015 0013 0015 0013 0014 0014 003b 0014 0014 0014 0014 0014 0014 0014 0014 0014 0014 0013 0015 0013 0015 0013 0015 0013 0015 0013 0014 0014 0014 0014 003b 0014 0014 0013 0015 0013 0015 0013 0014 0014 003b 0014 0015 0013 003b 0014 003b 0014 003b 0015 0013 0014 003b 0013 0f14",
        "24":"0000 006d 001e 0000 007b 0176 0013 003c 0015 0014 0013 0015 0013 0015 0013 003b 0014 0015 0013 0015 0013 0014 0014 0014 0014 0014 0014 0014 0013 0015 0014 0014 0013 0015 0013 0015 0013 0014 0014 003b 0014 0014 0014 0014 0013 003c 0013 0014 0014 003b 0014 0014 0015 003b 0013 003b 0014 003b 0014 003b 0014 0013 0015 0f14",
        "25":"0000 006d 001e 0000 007c 0174 0015 003a 0016 0013 0015 0013 0015 0013 0015 003a 0015 0013 0014 0014 0014 0014 0014 0013 0015 0013 0015 0013 0015 0013 0015 0013 0014 0014 0014 0014 0013 0015 0014 003b 0014 0014 0013 003c 0015 0013 0015 0013 0015 003a 0014 0014 0014 003a 0015 003a 0015 003b 0014 003a 0015 003a 0015 0f14",
        "26":"0000 006d 001e 0000 007f 0176 0015 003a 0014 0014 0014 0014 0014 0014 0014 003a 0015 0014 0014 0014 0014 0014 0014 0013 0015 0013 0014 0014 0014 0014 0014 0014 0014 0014 0014 0014 0011 0016 0014 003a 0015 0013 0014 003b 0013 003c 0013 0015 0015 003a 0014 0014 0015 003a 0013 0015 0011 0016 0014 0014 0014 0014 0014 0f14",
        "27":"0000 006d 001e 0000 007d 0177 0015 003a 0013 0015 0014 0016 0010 0016 0011 003d 0011 0016 0011 0015 0013 0015 0013 0015 0013 0015 0011 0016 0011 0016 0011 0016 0011 0015 0013 0015 0013 0015 0013 003d 0011 003d 0011 0015 0013 0015 0014 0015 0011 003d 0011 0016 0011 003c 0013 0015 0013 0015 0013 0015 0011 003d 0011 0f14",
        "28":"0000 006d 001e 0000 007e 0177 0015 003a 0013 0016 0011 0015 0013 0015 0013 003b 0014 0015 0013 0015 0011 0016 0011 0016 0011 0016 0011 0016 0011 0016 0011 0015 0013 0015 0013 0015 0013 0015 0011 003d 0011 003d 0011 0015 0013 003d 0011 0015 0013 003d 0011 0015 0013 003c 0013 0015 0013 0015 0013 003c 0011 0016 0011 0f14",
        "29":"0000 006d 001e 0000 007f 0175 0015 003a 0015 0013 0015 0013 0015 0013 0014 003b 0014 0014 0014 0014 0014 0014 0014 0014 0014 0013 0015 0013 0015 0013 0015 0013 0014 0014 0014 0014 0014 0014 0014 003a 0015 003a 0015 003a 0015 0013 0015 0013 0014 003b 0014 0014 0014 003a 0015 0013 0015 0013 0015 003a 0015 0039 0016 0f14",
        "30":"0000 006d 001e 0000 007f 0175 0015 003b 0015 0013 0015 0014 0013 0015 0013 003b 0015 0013 0014 0014 0015 0013 0014 0014 0013 0015 0013 0015 0013 0014 0014 0014 0014 0014 0014 0014 0011 0016 0014 003b 0014 003c 0013 003b 0014 003b 0014 0015 0013 003b 0014 0014 0014 003b 0014 0014 0014 003b 0014 0014 0014 0014 0014 0f14"
      },
      [truncated]
    }
  }
}

```

@vassilis-panos would you mind taking a look at this and potentially implementing it?

Thank you and best regards
